package com.pointlion.mvc.common.model;

import com.jfinal.kit.StrKit;
import com.jfinal.plugin.activerecord.Page;
import com.pointlion.mvc.common.model.base.BaseOaBumph1;
import com.pointlion.plugin.shiro.ShiroKit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OaBumph1 extends BaseOaBumph1<OaBumph1> {
	public static final OaBumph1 dao = new OaBumph1();
	public static final String TABLE_NAME = "oa_bumph";

	
	/***
	 * 获取分页
	 */
	public Page<OaBumph1> getPage(int pnum,int psize,String type){
		String sql = " from "+TABLE_NAME+" o LEFT JOIN act_hi_procinst p ON o.proc_ins_id=p.ID_ WHERE 1=1 ";
		String userId = ShiroKit.getUserId();
		//数据权限
		sql = sql + SysRoleOrg.dao.getRoleOrgSql(userId) ;
		if(StrKit.notBlank(type)){
			sql = sql + " AND o.type='"+type+"' ";
		}
		sql = sql + " ORDER BY create_time DESC";
		return OaBumph1.dao.paginate(pnum, psize, "select o.*,p.PROC_DEF_ID_ defid", sql);
	}
	
}
