package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaTabFile<M extends BaseOaTabFile<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setDocumentnumber(java.lang.String documentnumber) {
		set("documentnumber", documentnumber);
	}
	
	public java.lang.String getDocumentnumber() {
		return getStr("documentnumber");
	}

	public void setRegistrationdate(java.lang.String registrationdate) {
		set("registrationdate", registrationdate);
	}
	
	public java.lang.String getRegistrationdate() {
		return getStr("registrationdate");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}
	
	public java.lang.String getUserid() {
		return getStr("userid");
	}

	public void setTimeflag(java.lang.String timeflag) {
		set("timeflag", timeflag);
	}
	
	public java.lang.String getTimeflag() {
		return getStr("timeflag");
	}

	public void setFromdepart(java.lang.String fromdepart) {
		set("fromdepart", fromdepart);
	}
	
	public java.lang.String getFromdepart() {
		return getStr("fromdepart");
	}

	public void setDoucumentname(java.lang.String doucumentname) {
		set("doucumentname", doucumentname);
	}
	
	public java.lang.String getDoucumentname() {
		return getStr("doucumentname");
	}

	public void setWh(java.lang.String wh) {
		set("wh", wh);
	}
	
	public java.lang.String getWh() {
		return getStr("wh");
	}

	public void setTakedate(java.lang.String takedate) {
		set("takedate", takedate);
	}
	
	public java.lang.String getTakedate() {
		return getStr("takedate");
	}

	public void setNeedgd(java.lang.String needgd) {
		set("needgd", needgd);
	}
	
	public java.lang.String getNeedgd() {
		return getStr("needgd");
	}

	public void setLzqk(java.lang.String lzqk) {
		set("lzqk", lzqk);
	}
	
	public java.lang.String getLzqk() {
		return getStr("lzqk");
	}

	public void setClqk(java.lang.String clqk) {
		set("clqk", clqk);
	}
	
	public java.lang.String getClqk() {
		return getStr("clqk");
	}

	public void setZc(java.lang.String zc) {
		set("zc", zc);
	}
	
	public java.lang.String getZc() {
		return getStr("zc");
	}

}
