package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXdDict<M extends BaseXdDict<M>> extends Model<M> implements IBean {

	public void setId(String id) {
		set("id", id);
	}
	
	public String getId() {
		return getStr("id");
	}

	public void setName(String name) {
		set("name", name);
	}
	
	public String getName() {
		return getStr("name");
	}

	public void setKey(String key) {
		set("key", key);
	}
	
	public String getKey() {
		return getStr("key");
	}

	public void setValue(String value) {
		set("value", value);
	}
	
	public String getValue() {
		return getStr("value");
	}

	public void setType(String type) {
		set("type", type);
	}
	
	public String getType() {
		return getStr("type");
	}

	public void setCreateTime(String createTime) {
		set("create_time", createTime);
	}
	
	public String getCreateTime() {
		return getStr("create_time");
	}

	public void setDes(String des) {
		set("des", des);
	}
	
	public String getDes() {
		return getStr("des");
	}

	public void setGroupId(String groupId) {
		set("group_id", groupId);
	}
	
	public String getGroupId() {
		return getStr("group_id");
	}

	public void setSortnum(Integer sortnum) {
		set("sortnum", sortnum);
	}
	
	public Integer getSortnum() {
		return getInt("sortnum");
	}

}
