package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCrmCustomer<M extends BaseCrmCustomer<M>> extends Model<M> implements IBean {

	public void setId(String id) {
		set("id", id);
	}
	
	public String getId() {
		return getStr("id");
	}

	public void setUserid(String userid) {
		set("userid", userid);
	}
	
	public String getUserid() {
		return getStr("userid");
	}

	public void setCreateUserName(String createUserName) {
		set("create_user_name", createUserName);
	}
	
	public String getCreateUserName() {
		return getStr("create_user_name");
	}

	public void setOrgId(String createOrgId) {
		set("org_id", createOrgId);
	}
	
	public String getOrgId() {
		return getStr("org_id");
	}

	public void setCreateOrgName(String createOrgName) {
		set("create_org_name", createOrgName);
	}
	
	public String getCreateOrgName() {
		return getStr("create_org_name");
	}

	public void setCreateTime(String createTime) {
		set("create_time", createTime);
	}
	
	public String getCreateTime() {
		return getStr("create_time");
	}

	public void setName(String name) {
		set("name", name);
	}
	
	public String getName() {
		return getStr("name");
	}

	public void setCompanyId(String companyId) {
		set("company_id", companyId);
	}
	
	public String getCompanyId() {
		return getStr("company_id");
	}

	public void setCompanyName(String companyName) {
		set("company_name", companyName);
	}
	
	public String getCompanyName() {
		return getStr("company_name");
	}

	public void setOrg(String org) {
		set("org", org);
	}
	
	public String getOrg() {
		return getStr("org");
	}

	public void setWork(String work) {
		set("work", work);
	}
	
	public String getWork() {
		return getStr("work");
	}

	public void setWorkRelation(String workRelation) {
		set("work_relation", workRelation);
	}
	
	public String getWorkRelation() {
		return getStr("work_relation");
	}

	public void setMobile(String mobile) {
		set("mobile", mobile);
	}
	
	public String getMobile() {
		return getStr("mobile");
	}

	public void setEmail(String email) {
		set("email", email);
	}
	
	public String getEmail() {
		return getStr("email");
	}

	public void setBirthArea(String birthArea) {
		set("birth_area", birthArea);
	}
	
	public String getBirthArea() {
		return getStr("birth_area");
	}

	public void setAddress(String address) {
		set("address", address);
	}
	
	public String getAddress() {
		return getStr("address");
	}

	public void setImportantInfo(String importantInfo) {
		set("important_info", importantInfo);
	}
	
	public String getImportantInfo() {
		return getStr("important_info");
	}

	public void setLikeInfo(String likeInfo) {
		set("like_info", likeInfo);
	}
	
	public String getLikeInfo() {
		return getStr("like_info");
	}

	public void setIsImportant(String isImportant) {
		set("is_important", isImportant);
	}
	
	public String getIsImportant() {
		return getStr("is_important");
	}

	public void setNote(String note) {
		set("note", note);
	}
	
	public String getNote() {
		return getStr("note");
	}

	public void setIfSubmit(String ifSubmit) {
		set("if_submit", ifSubmit);
	}
	
	public String getIfSubmit() {
		return getStr("if_submit");
	}

	public void setIfComplete(String ifComplete) {
		set("if_complete", ifComplete);
	}
	
	public String getIfComplete() {
		return getStr("if_complete");
	}

	public void setIfAgree(String ifAgree) {
		set("if_agree", ifAgree);
	}
	
	public String getIfAgree() {
		return getStr("if_agree");
	}

	public void setProcInsId(String procInsId) {
		set("proc_ins_id", procInsId);
	}
	
	public String getProcInsId() {
		return getStr("proc_ins_id");
	}

}
