package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaEmailSon<M extends BaseOaEmailSon<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setOid(java.lang.String oid) {
		set("oid", oid);
	}
	
	public java.lang.String getOid() {
		return getStr("oid");
	}

	public void setSuserid(java.lang.String suserid) {
		set("suserid", suserid);
	}
	
	public java.lang.String getSuserid() {
		return getStr("suserid");
	}

	public void setSusername(java.lang.String susername) {
		set("susername", susername);
	}
	
	public java.lang.String getSusername() {
		return getStr("susername");
	}

	public void setFilenum(java.lang.String filenum) {
		set("filenum", filenum);
	}
	
	public java.lang.String getFilenum() {
		return getStr("filenum");
	}

	public void setIsreaded(java.lang.String isreaded) {
		set("isreaded", isreaded);
	}
	
	public java.lang.String getIsreaded() {
		return getStr("isreaded");
	}

	public void setFuserid(java.lang.String fuserid) {
		set("fuserid", fuserid);
	}
	
	public java.lang.String getFuserid() {
		return getStr("fuserid");
	}

	public void setFusername(java.lang.String fusername) {
		set("fusername", fusername);
	}
	
	public java.lang.String getFusername() {
		return getStr("fusername");
	}

	public void setStime(java.lang.String stime) {
		set("stime", stime);
	}
	
	public java.lang.String getStime() {
		return getStr("stime");
	}

	public void setFtime(java.lang.String ftime) {
		set("ftime", ftime);
	}
	
	public java.lang.String getFtime() {
		return getStr("ftime");
	}

	public void setCuserid(java.lang.String cuserid) {
		set("cuserid", cuserid);
	}
	
	public java.lang.String getCuserid() {
		return getStr("cuserid");
	}

	public void setCusername(java.lang.String cusername) {
		set("cusername", cusername);
	}
	
	public java.lang.String getCusername() {
		return getStr("cusername");
	}

	public void setCtime(java.lang.String ctime) {
		set("ctime", ctime);
	}
	
	public java.lang.String getCtime() {
		return getStr("ctime");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setDtime(java.lang.String dtime) {
		set("dtime", dtime);
	}
	
	public java.lang.String getDtime() {
		return getStr("dtime");
	}

}
