package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXdScheduleDetail<M extends BaseXdScheduleDetail<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}
	
	public Long getId() {
		return getLong("id");
	}

	public void setScheduleId(String scheduleId) {
		set("schedule_id", scheduleId);
	}
	
	public String getScheduleId() {
		return getStr("schedule_id");
	}

	public void setShiftName(String shiftName) {
		set("shift_name", shiftName);
	}
	
	public String getShiftName() {
		return getStr("shift_name");
	}

	public void setWorkHours(String workHours) {
		set("work_hours", workHours);
	}
	
	public String getWorkHours() {
		return getStr("work_hours");
	}

	public void setMiddleNightShift(String middleNightShift) {
		set("middle_night_shift", middleNightShift);
	}
	
	public String getMiddleNightShift() {
		return getStr("middle_night_shift");
	}

	public void setScheduleYear(String scheduleYear) {
		set("schedule_year", scheduleYear);
	}
	
	public String getScheduleYear() {
		return getStr("schedule_year");
	}

	public void setScheduleMonth(String scheduleMonth) {
		set("schedule_month", scheduleMonth);
	}
	
	public String getScheduleMonth() {
		return getStr("schedule_month");
	}

	public void setScheduleDay(String scheduleDay) {
		set("schedule_day", scheduleDay);
	}
	
	public String getScheduleDay() {
		return getStr("schedule_day");
	}

	public void setScheduleYmd(String scheduleYmd) {
		set("schedule_ymd", scheduleYmd);
	}
	
	public String getScheduleYmd() {
		return getStr("schedule_ymd");
	}

	public void setWeekDay(String weekDay) {
		set("week_day", weekDay);
	}
	
	public String getWeekDay() {
		return getStr("week_day");
	}

	public void setHolidays(String holidays) {
		set("holidays", holidays);
	}
	
	public String getHolidays() {
		return getStr("holidays");
	}

	public void setStatus(String status) {
		set("status", status);
	}
	
	public String getStatus() {
		return getStr("status");
	}

	public void setCreateUser(String createUser) {
		set("create_user", createUser);
	}
	
	public String getCreateUser() {
		return getStr("create_user");
	}

	public void setCreateDate(String createDate) {
		set("create_date", createDate);
	}
	
	public String getCreateDate() {
		return getStr("create_date");
	}

	public void setUpdateUser(String updateUser) {
		set("update_user", updateUser);
	}
	
	public String getUpdateUser() {
		return getStr("update_user");
	}

	public void setUpdateDate(String updateDate) {
		set("update_date", updateDate);
	}
	
	public String getUpdateDate() {
		return getStr("update_date");
	}

}
