package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaNodes<M extends BaseOaNodes<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setNodename(java.lang.String nodename) {
		set("nodename", nodename);
	}
	
	public java.lang.String getNodename() {
		return getStr("nodename");
	}

	public void setStartnode(java.lang.String startnode) {
		set("startnode", startnode);
	}
	
	public java.lang.String getStartnode() {
		return getStr("startnode");
	}

	public void setEndnode(java.lang.String endnode) {
		set("endnode", endnode);
	}
	
	public java.lang.String getEndnode() {
		return getStr("endnode");
	}

	public void setNodecomplete(java.lang.String nodecomplete) {
		set("nodecomplete", nodecomplete);
	}
	
	public java.lang.String getNodecomplete() {
		return getStr("nodecomplete");
	}

	public void setCompletetime(java.lang.String completetime) {
		set("completetime", completetime);
	}
	
	public java.lang.String getCompletetime() {
		return getStr("completetime");
	}

	public void setNodecando(java.lang.String nodecando) {
		set("nodecando", nodecando);
	}
	
	public java.lang.String getNodecando() {
		return getStr("nodecando");
	}

	public void setOrgid(java.lang.String orgid) {
		set("orgid", orgid);
	}
	
	public java.lang.String getOrgid() {
		return getStr("orgid");
	}

	public void setParentid(java.lang.String parentid) {
		set("parentid", parentid);
	}
	
	public java.lang.String getParentid() {
		return getStr("parentid");
	}

	public void setSortnum(java.lang.Integer sortnum) {
		set("sortnum", sortnum);
	}
	
	public java.lang.Integer getSortnum() {
		return getInt("sortnum");
	}

	public void setOid(java.lang.String oid) {
		set("oid", oid);
	}
	
	public java.lang.String getOid() {
		return getStr("oid");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setCuserid(java.lang.String cuserid) {
		set("cuserid", cuserid);
	}
	
	public java.lang.String getCuserid() {
		return getStr("cuserid");
	}

	public void setCusername(java.lang.String cusername) {
		set("cusername", cusername);
	}
	
	public java.lang.String getCusername() {
		return getStr("cusername");
	}

	public void setCtime(java.lang.String ctime) {
		set("ctime", ctime);
	}
	
	public java.lang.String getCtime() {
		return getStr("ctime");
	}

	public void setBackup1(java.lang.String backup1) {
		set("backup1", backup1);
	}
	
	public java.lang.String getBackup1() {
		return getStr("backup1");
	}

	public void setBackup2(java.lang.String backup2) {
		set("backup2", backup2);
	}
	
	public java.lang.String getBackup2() {
		return getStr("backup2");
	}

	public void setBackup3(java.lang.String backup3) {
		set("backup3", backup3);
	}
	
	public java.lang.String getBackup3() {
		return getStr("backup3");
	}

}
