package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXdCertLog<M extends BaseXdCertLog<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}
	
	public Long getId() {
		return getLong("id");
	}

	public void setYear(Integer year) {
		set("year", year);
	}
	
	public Integer getYear() {
		return getInt("year");
	}

	public void setMonth(Integer month) {
		set("month", month);
	}
	
	public Integer getMonth() {
		return getInt("month");
	}

	public void setDeptId(String deptId) {
		set("dept_id", deptId);
	}
	
	public String getDeptId() {
		return getStr("dept_id");
	}

	public void setDeptName(String deptName) {
		set("dept_name", deptName);
	}
	
	public String getDeptName() {
		return getStr("dept_name");
	}

	public void setEid(String eid) {
		set("eid", eid);
	}
	
	public String getEid() {
		return getStr("eid");
	}

	public void setEname(String ename) {
		set("ename", ename);
	}
	
	public String getEname() {
		return getStr("ename");
	}

	public void setCertTitle(String certTitle) {
		set("cert_title", certTitle);
	}
	
	public String getCertTitle() {
		return getStr("cert_title");
	}

	public void setLogType(String logType) {
		set("log_type", logType);
	}
	
	public String getLogType() {
		return getStr("log_type");
	}

	public void setNum(Integer num) {
		set("num", num);
	}
	
	public Integer getNum() {
		return getInt("num");
	}

	public void setMonthCert(String monthCert) {
		set("month_cert", monthCert);
	}
	
	public String getMonthCert() {
		return getStr("month_cert");
	}

	public void setRemark1(String remark1) {
		set("remark1", remark1);
	}
	
	public String getRemark1() {
		return getStr("remark1");
	}

	public void setRemark2(String remark2) {
		set("remark2", remark2);
	}
	
	public String getRemark2() {
		return getStr("remark2");
	}

	public void setCreateDate(String createDate) {
		set("create_date", createDate);
	}
	
	public String getCreateDate() {
		return getStr("create_date");
	}

	public void setCreateUser(String createUser) {
		set("create_user", createUser);
	}
	
	public String getCreateUser() {
		return getStr("create_user");
	}

}
