package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseToolWeight<M extends BaseToolWeight<M>> extends Model<M> implements IBean {

	public void setId(String id) {
		set("id", id);
	}
	
	public String getId() {
		return getStr("id");
	}

	public void setCrdateTime(String crdateTime) {
		set("crdate_time", crdateTime);
	}
	
	public String getCrdateTime() {
		return getStr("crdate_time");
	}

	public void setWeight1(String weight1) {
		set("weight1", weight1);
	}
	
	public String getWeight1() {
		return getStr("weight1");
	}

	public void setWeight2(String weight2) {
		set("weight2", weight2);
	}
	
	public String getWeight2() {
		return getStr("weight2");
	}

	public void setWeight3(String weight3) {
		set("weight3", weight3);
	}
	
	public String getWeight3() {
		return getStr("weight3");
	}

	public void setCarNum(String carNum) {
		set("car_num", carNum);
	}
	
	public String getCarNum() {
		return getStr("car_num");
	}

	public void setCustomer(String customer) {
		set("customer", customer);
	}
	
	public String getCustomer() {
		return getStr("customer");
	}

	public void setBigWeight(String bigWeight) {
		set("big_weight", bigWeight);
	}
	
	public String getBigWeight() {
		return getStr("big_weight");
	}

	public void setOrgName(String org_name) {
		set("org_name", org_name);
	}

	public String getOrgName() {
		return getStr("big_weight");
	}

	public void setPinName(String pin_name) {
		set("pin_name", pin_name);
	}

	public String getPinName() {
		return getStr("pin_name");
	}
}
