package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import com.pointlion.mvc.common.model.OaDictGroup;
import com.pointlion.mvc.common.model.XdDictGroup;

import java.util.List;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXdDictGroup<M extends BaseXdDictGroup<M>> extends Model<M> implements IBean {

	private List<XdDictGroup> children;

	public List<XdDictGroup> getChildren() {
		return children;
	}
	public void setChildren(List<XdDictGroup> children) {
		this.children = children;
	}
	public void setId(String id) {
		set("id", id);
	}
	
	public String getId() {
		return getStr("id");
	}

	public void setKey(String key) {
		set("key", key);
	}
	
	public String getKey() {
		return getStr("key");
	}

	public void setName(String name) {
		set("name", name);
	}
	
	public String getName() {
		return getStr("name");
	}

	public void setParentId(String parentId) {
		set("parent_id", parentId);
	}
	
	public String getParentId() {
		return getStr("parent_id");
	}

	public void setDes(String des) {
		set("des", des);
	}
	
	public String getDes() {
		return getStr("des");
	}

	public void setSort(Long sort) {
		set("sort", sort);
	}
	
	public Long getSort() {
		return getLong("sort");
	}

}
