package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCrmOrder<M extends BaseCrmOrder<M>> extends Model<M> implements IBean {

	public void setId(String id) {
		set("id", id);
	}
	
	public String getId() {
		return getStr("id");
	}

	public void setUserid(String userid) {
		set("userid", userid);
	}
	
	public String getUserid() {
		return getStr("userid");
	}

	public void setCreateUserName(String createUserName) {
		set("create_user_name", createUserName);
	}
	
	public String getCreateUserName() {
		return getStr("create_user_name");
	}

	public void setOrgId(String orgId) {
		set("org_id", orgId);
	}
	
	public String getOrgId() {
		return getStr("org_id");
	}

	public void setOrgName(String orgName) {
		set("org_name", orgName);
	}
	
	public String getOrgName() {
		return getStr("org_name");
	}

	public void setNum(String num) {
		set("num", num);
	}
	
	public String getNum() {
		return getStr("num");
	}

	public void setOrderDate(String orderDate) {
		set("order_date", orderDate);
	}
	
	public String getOrderDate() {
		return getStr("order_date");
	}

	public void setProjectId(String projectId) {
		set("project_id", projectId);
	}
	
	public String getProjectId() {
		return getStr("project_id");
	}

	public java.lang.String getProjectCode() {
		return get("project_code");
	}

	public void setProjectCode(java.lang.String project_code) {
		set("project_code", project_code);
	}

	public void setProjectName(String projectName) {
		set("project_name", projectName);
	}
	
	public String getProjectName() {
		return getStr("project_name");
	}

	public void setCustomerId(String customerId) {
		set("customer_id", customerId);
	}
	
	public String getCustomerId() {
		return getStr("customer_id");
	}

	public void setCustomerName(String customerName) {
		set("customer_name", customerName);
	}
	
	public String getCustomerName() {
		return getStr("customer_name");
	}

	public void setCustomerCode(String customer_code) {
		set("customer_code", customer_code);
	}

	public String getCustomerCode() {
		return getStr("customer_code");
	}

	public void setTypeName(String typeName) {
		set("type_name", typeName);
	}
	
	public String getTypeName() {
		return getStr("type_name");
	}

	public void setOrderCount(String orderCount) {
		set("order_count", orderCount);
	}
	
	public String getOrderCount() {
		return getStr("order_count");
	}

	public void setPrice(String price) {
		set("price", price);
	}
	
	public String getPrice() {
		return getStr("price");
	}

	public void setMoney(String money) {
		set("money", money);
	}
	
	public String getMoney() {
		return getStr("money");
	}

	public void setProductCount(String productCount) {
		set("product_count", productCount);
	}
	
	public String getProductCount() {
		return getStr("product_count");
	}

	public void setOutPdtDate(String outPdtDate) {
		set("out_pdt_date", outPdtDate);
	}
	
	public String getOutPdtDate() {
		return getStr("out_pdt_date");
	}

	public void setReceivePdtDate(String receivePdtDate) {
		set("receive_pdt_date", receivePdtDate);
	}
	
	public String getReceivePdtDate() {
		return getStr("receive_pdt_date");
	}

	public void setAccountDate(String accountDate) {
		set("account_date", accountDate);
	}
	
	public String getAccountDate() {
		return getStr("account_date");
	}

	public void setInvoiceDate(String invoiceDate) {
		set("invoice_date", invoiceDate);
	}
	
	public String getInvoiceDate() {
		return getStr("invoice_date");
	}

	public void setInvoiceCode(String invoiceCode) {
		set("invoice_code", invoiceCode);
	}
	
	public String getInvoiceCode() {
		return getStr("invoice_code");
	}

	public void setInvoiceMoney(String invoiceMoney) {
		set("invoice_money", invoiceMoney);
	}
	
	public String getInvoiceMoney() {
		return getStr("invoice_money");
	}

	public void setPayDate(String payDate) {
		set("pay_date", payDate);
	}
	
	public String getPayDate() {
		return getStr("pay_date");
	}

	public void setPayMoney(String payMoney) {
		set("pay_money", payMoney);
	}
	
	public String getPayMoney() {
		return getStr("pay_money");
	}

	public void setOperateUserid(String operateUserid) {
		set("operate_userid", operateUserid);
	}
	
	public String getOperateUserid() {
		return getStr("operate_userid");
	}

	public void setOperateUserName(String operateUserName) {
		set("operate_user_name", operateUserName);
	}
	
	public String getOperateUserName() {
		return getStr("operate_user_name");
	}

	public void setDes(String des) {
		set("des", des);
	}
	
	public String getDes() {
		return getStr("des");
	}

	public void setCreateTime(String createTime) {
		set("create_time", createTime);
	}
	
	public String getCreateTime() {
		return get("create_time");
	}

	public void setIfSubmit(String ifSubmit) {
		set("if_submit", ifSubmit);
	}

	public String getIfSubmit() {
		return getStr("if_submit");
	}

	public void setIfComplete(String ifComplete) {
		set("if_complete", ifComplete);
	}

	public String getIfComplete() {
		return getStr("if_complete");
	}

	public void setIfAgree(String ifAgree) {
		set("if_agree", ifAgree);
	}

	public String getIfAgree() {
		return getStr("if_agree");
	}

	public void setProcInsId(String procInsId) {
		set("proc_ins_id", procInsId);
	}

	public String getProcInsId() {
		return getStr("proc_ins_id");
	}

	public void setOrderCode(String order_code) {
		set("order_code", order_code);
	}

	public String getOrderCode() {
		return getStr("order_code");
	}

	public void setPoCount(String po_count) {
		set("po_count", po_count);
	}

	public String getPoCount() {
		return getStr("po_count");
	}

	public void setSellCount(String sell_count) {
		set("sell_count", sell_count);
	}

	public String getSellCount() {
		return getStr("sell_count");
	}

	public void setDollar(String dollar) {
		set("dollar", dollar);
	}

	public String getDollar() {
		return getStr("dollar");
	}

	public void setWaitCount(String wait_count) {
		set("wait_count", wait_count);
	}

	public String getWaitCount() {
		return getStr("wait_count");
	}

	public void setExchangeRate(String exchange_rate) {
		set("exchange_rate", exchange_rate);
	}

	public String getExchangeRate() {
		return getStr("exchange_rate");
	}

	public void setLifelessCount(String lifeless_count) {
		set("lifeless_count", lifeless_count);
	}

	public String getLifelessCount() {
		return getStr("lifeless_count");
	}

	public void setOrderNum(String order_num) {
		set("order_num", order_num);
	}

	public String getOrderNum() {
		return getStr("order_num");
	}

}
