package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXdScheduleSummary<M extends BaseXdScheduleSummary<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}
	
	public Long getId() {
		return getLong("id");
	}

	public void setDeptValue(String deptValue) {
		set("dept_value", deptValue);
	}
	
	public String getDeptValue() {
		return getStr("dept_value");
	}

	public void setDeptName(String deptName) {
		set("dept_name", deptName);
	}
	
	public String getDeptName() {
		return getStr("dept_name");
	}

	public void setUnitValue(String unitValue) {
		set("unit_value", unitValue);
	}
	
	public String getUnitValue() {
		return getStr("unit_value");
	}

	public void setUnitName(String unitName) {
		set("unit_name", unitName);
	}
	
	public String getUnitName() {
		return getStr("unit_name");
	}

	public void setEmpNum(String empNum) {
		set("emp_num", empNum);
	}
	
	public String getEmpNum() {
		return getStr("emp_num");
	}

	public void setEmpId(String empId) {
		set("emp_id", empId);
	}
	
	public String getEmpId() {
		return getStr("emp_id");
	}

	public void setEmpName(String empName) {
		set("emp_name", empName);
	}
	
	public String getEmpName() {
		return getStr("emp_name");
	}

	public void setWorkStation(String workStation) {
		set("work_station", workStation);
	}
	
	public String getWorkStation() {
		return getStr("work_station");
	}

	public void setScheduleYear(String scheduleYear) {
		set("schedule_year", scheduleYear);
	}
	
	public String getScheduleYear() {
		return getStr("schedule_year");
	}

	public void setScheduleMonth(String scheduleMonth) {
		set("schedule_month", scheduleMonth);
	}
	
	public String getScheduleMonth() {
		return getStr("schedule_month");
	}

	public void setScheduleYearMonth(String scheduleYearMonth) {
		set("schedule_year_month", scheduleYearMonth);
	}
	
	public String getScheduleYearMonth() {
		return getStr("schedule_year_month");
	}

	public void setRemarks(String remarks) {
		set("remarks", remarks);
	}
	
	public String getRemarks() {
		return getStr("remarks");
	}

	public void setStatus(String status) {
		set("status", status);
	}
	
	public String getStatus() {
		return getStr("status");
	}

	public void setCreateUser(String createUser) {
		set("create_user", createUser);
	}
	
	public String getCreateUser() {
		return getStr("create_user");
	}

	public void setCreateDate(String createDate) {
		set("create_date", createDate);
	}
	
	public String getCreateDate() {
		return getStr("create_date");
	}

	public void setUpdateUser(String updateUser) {
		set("update_user", updateUser);
	}
	
	public String getUpdateUser() {
		return getStr("update_user");
	}

	public void setUpdateDate(String updateDate) {
		set("update_date", updateDate);
	}
	
	public String getUpdateDate() {
		return getStr("update_date");
	}

}
