package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaNotices<M extends BaseOaNotices<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setNoticename(java.lang.String noticename) {
		set("noticename", noticename);
	}
	
	public java.lang.String getNoticename() {
		return getStr("noticename");
	}

	public void setNoticeinfo(java.lang.String noticeinfo) {
		set("noticeinfo", noticeinfo);
	}
	
	public java.lang.String getNoticeinfo() {
		return getStr("noticeinfo");
	}

	public void setOpuser(java.lang.String opuser) {
		set("opuser", opuser);
	}
	
	public java.lang.String getOpuser() {
		return getStr("opuser");
	}

	public void setChangetime(java.lang.String changetime) {
		set("changetime", changetime);
	}
	
	public java.lang.String getChangetime() {
		return getStr("changetime");
	}

	public void setSfshowhomepage(java.lang.String sfshowhomepage) {
		set("sfshowhomepage", sfshowhomepage);
	}
	
	public java.lang.String getSfshowhomepage() {
		return getStr("sfshowhomepage");
	}

	public void setShowtime(java.lang.String showtime) {
		set("showtime", showtime);
	}
	
	public java.lang.String getShowtime() {
		return getStr("showtime");
	}

	public void setShowhomepageinfo(java.lang.String showhomepageinfo) {
		set("showhomepageinfo", showhomepageinfo);
	}
	
	public java.lang.String getShowhomepageinfo() {
		return getStr("showhomepageinfo");
	}

	public void setSfpublish(java.lang.String sfpublish) {
		set("sfpublish", sfpublish);
	}
	
	public java.lang.String getSfpublish() {
		return getStr("sfpublish");
	}

	public void setPublisher(java.lang.String publisher) {
		set("publisher", publisher);
	}
	
	public java.lang.String getPublisher() {
		return getStr("publisher");
	}

	public void setPublishdatetime(java.lang.String publishdatetime) {
		set("publishdatetime", publishdatetime);
	}
	
	public java.lang.String getPublishdatetime() {
		return getStr("publishdatetime");
	}

	public void setOpuserid(java.lang.String opuserid) {
		set("opuserid", opuserid);
	}
	
	public java.lang.String getOpuserid() {
		return getStr("opuserid");
	}

	public void setPublisherid(java.lang.String publisherid) {
		set("publisherid", publisherid);
	}
	
	public java.lang.String getPublisherid() {
		return getStr("publisherid");
	}

	public void setDepartments(java.lang.String departments) {
		set("departments", departments);
	}
	
	public java.lang.String getDepartments() {
		return getStr("departments");
	}

}
