package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysUser<M extends BaseSysUser<M>> extends Model<M> implements IBean {

	public void setId(String id) {
		set("id", id);
	}
	
	public String getId() {
		return getStr("id");
	}

	public void setUsername(String username) {
		set("username", username);
	}
	
	public String getUsername() {
		return getStr("username");
	}

	public void setPassword(String password) {
		set("password", password);
	}
	
	public String getPassword() {
		return getStr("password");
	}

	public void setName(String name) {
		set("name", name);
	}
	
	public String getName() {
		return getStr("name");
	}

	public void setSex(String sex) {
		set("sex", sex);
	}
	
	public String getSex() {
		return getStr("sex");
	}

	public void setStatus(String status) {
		set("status", status);
	}
	
	public String getStatus() {
		return getStr("status");
	}

	public void setOrgid(String orgid) {
		set("orgid", orgid);
	}
	
	public String getOrgid() {
		return getStr("orgid");
	}

	public void setStationid(String stationid) {
		set("stationid", stationid);
	}
	
	public String getStationid() {
		return getStr("stationid");
	}

	public void setEmail(String email) {
		set("email", email);
	}
	
	public String getEmail() {
		return getStr("email");
	}

	public void setIdcard(String idcard) {
		set("idcard", idcard);
	}
	
	public String getIdcard() {
		return getStr("idcard");
	}

	public void setIsAdmin(String isAdmin) {
		set("is_admin", isAdmin);
	}
	
	public String getIsAdmin() {
		return getStr("is_admin");
	}

	public void setSort(Long sort) {
		set("sort", sort);
	}
	
	public Long getSort() {
		return getLong("sort");
	}

	public void setMobile(String mobile) {
		set("mobile", mobile);
	}
	
	public String getMobile() {
		return getStr("mobile");
	}

	public void setImg(String img) {
		set("img", img);
	}
	
	public String getImg() {
		return getStr("img");
	}

	public void setType(String type) {
		set("type", type);
	}
	
	public String getType() {
		return getStr("type");
	}

	public void setEntryDate(String entryDate) {
		set("entry_date", entryDate);
	}
	
	public String getEntryDate() {
		return getStr("entry_date");
	}

	public void setBirthDate(String birthDate) {
		set("birth_date", birthDate);
	}
	
	public String getBirthDate() {
		return getStr("birth_date");
	}

	public void setYearHoliday(String yearHoliday) {
		set("year_holiday", yearHoliday);
	}
	
	public String getYearHoliday() {
		return getStr("year_holiday");
	}

	public void setSignNamePic(String signNamePic) {
		set("sign_name_pic", signNamePic);
	}
	
	public String getSignNamePic() {
		return getStr("sign_name_pic");
	}

	public void setInCompanyDate(String inCompanyDate) {
		set("in_company_date", inCompanyDate);
	}
	
	public String getInCompanyDate() {
		return getStr("in_company_date");
	}

	public void setDimissionDate(String dimissionDate) {
		set("dimission_date", dimissionDate);
	}
	
	public String getDimissionDate() {
		return getStr("dimission_date");
	}

	public void setExperience(String experience) {
		set("experience", experience);
	}
	
	public String getExperience() {
		return getStr("experience");
	}

	public void setEduExperience(String eduExperience) {
		set("edu_experience", eduExperience);
	}
	
	public String getEduExperience() {
		return getStr("edu_experience");
	}

	public void setWorkNum(String workNum) {
		set("work_num", workNum);
	}
	
	public String getWorkNum() {
		return getStr("work_num");
	}

	public void setPosition(String position) {
		set("position", position);
	}
	
	public String getPosition() {
		return getStr("position");
	}

	public void setUnitValue(String unitValue) {
		set("unit_value", unitValue);
	}
	
	public String getUnitValue() {
		return getStr("unit_value");
	}

	public void setUnitName(String unitName) {
		set("unit_name", unitName);
	}
	
	public String getUnitName() {
		return getStr("unit_name");
	}

	public void setEmpId(String empId) {
		set("emp_id", empId);
	}
	
	public String getEmpId() {
		return getStr("emp_id");
	}

	public void setOperProject(String operProject) {
		set("oper_project", operProject);
	}
	
	public String getOperProject() {
		return getStr("oper_project");
	}

}
