package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXdSettleOvertimeSummary<M extends BaseXdSettleOvertimeSummary<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}
	
	public Long getId() {
		return getLong("id");
	}

	public void setEmpNum(String empNum) {
		set("emp_num", empNum);
	}
	
	public String getEmpNum() {
		return getStr("emp_num");
	}

	public void setEmpName(String empName) {
		set("emp_name", empName);
	}
	
	public String getEmpName() {
		return getStr("emp_name");
	}

	public void setEmpIdnum(String empIdnum) {
		set("emp_idnum", empIdnum);
	}
	
	public String getEmpIdnum() {
		return getStr("emp_idnum");
	}

	public void setDeptId(String deptId) {
		set("dept_id", deptId);
	}
	
	public String getDeptId() {
		return getStr("dept_id");
	}

	public void setDeptName(String deptName) {
		set("dept_name", deptName);
	}
	
	public String getDeptName() {
		return getStr("dept_name");
	}

	public void setProjectId(String projectId) {
		set("project_id", projectId);
	}
	
	public String getProjectId() {
		return getStr("project_id");
	}

	public void setProjectName(String projectName) {
		set("project_name", projectName);
	}
	
	public String getProjectName() {
		return getStr("project_name");
	}

	public void setApplyDate(String applyDate) {
		set("apply_date", applyDate);
	}
	
	public String getApplyDate() {
		return getStr("apply_date");
	}

	public void setApplyStart(String applyStart) {
		set("apply_start", applyStart);
	}
	
	public String getApplyStart() {
		return getStr("apply_start");
	}

	public void setApplyEnd(String applyEnd) {
		set("apply_end", applyEnd);
	}
	
	public String getApplyEnd() {
		return getStr("apply_end");
	}

	public void setApplyHours(String applyHours) {
		set("apply_hours", applyHours);
	}
	
	public String getApplyHours() {
		return getStr("apply_hours");
	}

	public void setApplyType(String applyType) {
		set("apply_type", applyType);
	}
	
	public String getApplyType() {
		return getStr("apply_type");
	}

	public void setActStart(String actStart) {
		set("act_start", actStart);
	}
	
	public String getActStart() {
		return getStr("act_start");
	}

	public void setActEnd(String actEnd) {
		set("act_end", actEnd);
	}
	
	public String getActEnd() {
		return getStr("act_end");
	}

	public void setActHours(String actHours) {
		set("act_hours", actHours);
	}
	
	public String getActHours() {
		return getStr("act_hours");
	}

	public void setRemarks(String remarks) {
		set("remarks", remarks);
	}
	
	public String getRemarks() {
		return getStr("remarks");
	}

	public void setStatus(String status) {
		set("status", status);
	}
	
	public String getStatus() {
		return getStr("status");
	}

	public void setCreateUser(String createUser) {
		set("create_user", createUser);
	}
	
	public String getCreateUser() {
		return getStr("create_user");
	}

	public void setCreateDate(String createDate) {
		set("create_date", createDate);
	}
	
	public String getCreateDate() {
		return getStr("create_date");
	}

}
