package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaRz<M extends BaseOaRz<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

	public void setOid(java.lang.String oid) {
		set("oid", oid);
	}
	
	public java.lang.String getOid() {
		return getStr("oid");
	}

	public void setKeywords(java.lang.String keywords) {
		set("keywords", keywords);
	}
	
	public java.lang.String getKeywords() {
		return getStr("keywords");
	}

	public void setCuser(java.lang.String cuser) {
		set("cuser", cuser);
	}
	
	public java.lang.String getCuser() {
		return getStr("cuser");
	}

	public void setCtime(java.lang.String ctime) {
		set("ctime", ctime);
	}
	
	public java.lang.String getCtime() {
		return getStr("ctime");
	}

	public void setBackup1(java.lang.String backup1) {
		set("backup1", backup1);
	}
	
	public java.lang.String getBackup1() {
		return getStr("backup1");
	}

	public void setBackup2(java.lang.String backup2) {
		set("backup2", backup2);
	}
	
	public java.lang.String getBackup2() {
		return getStr("backup2");
	}

	public void setBackup3(java.lang.String backup3) {
		set("backup3", backup3);
	}
	
	public java.lang.String getBackup3() {
		return getStr("backup3");
	}

}
