package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaApplyBorrowMoney<M extends BaseOaApplyBorrowMoney<M>> extends Model<M> implements IBean {

	public void setId(String id) {
		set("id", id);
	}
	
	public String getId() {
		return getStr("id");
	}

	public void setUserid(String userid) {
		set("userid", userid);
	}
	
	public String getUserid() {
		return getStr("userid");
	}

	public void setApplyerName(String applyerName) {
		set("applyer_name", applyerName);
	}
	
	public String getApplyerName() {
		return getStr("applyer_name");
	}

	public void setOrgId(String orgId) {
		set("org_id", orgId);
	}
	
	public String getOrgId() {
		return getStr("org_id");
	}

	public void setOrgName(String orgName) {
		set("org_name", orgName);
	}
	
	public String getOrgName() {
		return getStr("org_name");
	}

	public void setIfSubmit(String ifSubmit) {
		set("if_submit", ifSubmit);
	}
	
	public String getIfSubmit() {
		return getStr("if_submit");
	}

	public void setIfComplete(String ifComplete) {
		set("if_complete", ifComplete);
	}
	
	public String getIfComplete() {
		return getStr("if_complete");
	}

	public void setIfAgree(String ifAgree) {
		set("if_agree", ifAgree);
	}
	
	public String getIfAgree() {
		return getStr("if_agree");
	}

	public void setProcInsId(String procInsId) {
		set("proc_ins_id", procInsId);
	}
	
	public String getProcInsId() {
		return getStr("proc_ins_id");
	}

	public void setCreateTime(String createTime) {
		set("create_time", createTime);
	}
	
	public String getCreateTime() {
		return getStr("create_time");
	}

	public void setDes(String des) {
		set("des", des);
	}
	
	public String getDes() {
		return getStr("des");
	}

	public void setNote(String note) {
		set("note", note);
	}
	
	public String getNote() {
		return getStr("note");
	}

	public void setPayType(String payType) {
		set("pay_type", payType);
	}
	
	public String getPayType() {
		return getStr("pay_type");
	}

	public void setRepayType(String repayType) {
		set("repay_type", repayType);
	}
	
	public String getRepayType() {
		return getStr("repay_type");
	}

	public void setMoney(String money) {
		set("money", money);
	}
	
	public String getMoney() {
		return getStr("money");
	}

	public void setRepayDate(String repayDate) {
		set("repay_date", repayDate);
	}
	
	public String getRepayDate() {
		return getStr("repay_date");
	}


	//  自增
// public void setNum(String num) {
//    set("num", num);
// }

	public String getNum() {
		return getStr("num");
	}

	//自增
	public void setCode(String code) {
		set("code", code);
	}

	public String geCode() {
		return getStr("code");
	}


	public void setCreateUserId(String create_user_id) {
		set("create_user_id", create_user_id);
	}

	public String getCreateUserId() {
		return get("create_user_id");
	}

	public void setCreateUserName(String create_user_name) {
		set("create_user_name", create_user_name);
	}

	public String getCreateUserName() {
		return get("create_user_name");
	}

	public void setCreateOrgId(String create_org_id) {
		set("create_org_id", create_org_id);
	}

	public String getCreateOrgId() {
		return get("create_org_id");
	}

	public void setCreateOrgName(String create_org_name) {
		set("create_org_name", create_org_name);
	}

	public String getCreateOrgName() {
		return get("create_org_name");
	}
}
