package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXdAttendanceSheet<M extends BaseXdAttendanceSheet<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	public void setSummaryId(String summaryId) {
		set("summary_id", summaryId);
	}
	
	public String getSummaryId() {
		return getStr("summary_id");
	}

	public void setYear(Integer year) {
		set("year", year);
	}
	
	public Integer getYear() {
		return getInt("year");
	}

	public void setMonth(Integer month) {
		set("month", month);
	}
	
	public Integer getMonth() {
		return getInt("month");
	}

	public void setYearMonth(String yearMonth) {
		set("year_month", yearMonth);
	}
	
	public String getYearMonth() {
		return getStr("year_month");
	}

	public void setDeptId(String deptId) {
		set("dept_id", deptId);
	}
	
	public String getDeptId() {
		return getStr("dept_id");
	}

	public void setDeptName(String deptName) {
		set("dept_name", deptName);
	}
	
	public String getDeptName() {
		return getStr("dept_name");
	}

	public void setUnitId(String unitId) {
		set("unit_id", unitId);
	}
	
	public String getUnitId() {
		return getStr("unit_id");
	}

	public void setUnitName(String unitName) {
		set("unit_name", unitName);
	}
	
	public String getUnitName() {
		return getStr("unit_name");
	}

	public void setProjectId(String projectId) {
		set("project_id", projectId);
	}
	
	public String getProjectId() {
		return getStr("project_id");
	}

	public void setProjectName(String projectName) {
		set("project_name", projectName);
	}
	
	public String getProjectName() {
		return getStr("project_name");
	}

	public void setEmpNum(String empNum) {
		set("emp_num", empNum);
	}
	
	public String getEmpNum() {
		return getStr("emp_num");
	}

	public void setEmpName(String empName) {
		set("emp_name", empName);
	}
	
	public String getEmpName() {
		return getStr("emp_name");
	}

	public void setIdNum(String idNum) {
		set("id_num", idNum);
	}
	
	public String getIdNum() {
		return getStr("id_num");
	}

	public void setOrdinaryOt(String ordinaryOt) {
		set("ordinary_ot", ordinaryOt);
	}
	
	public String getOrdinaryOt() {
		return getStr("ordinary_ot");
	}

	public void setTdayWeekendOt(String tdayWeekendOt) {
		set("tday_weekend_ot", tdayWeekendOt);
	}
	
	public String getTdayWeekendOt() {
		return getStr("tday_weekend_ot");
	}

	public void setNationalOt(String nationalOt) {
		set("national_ot", nationalOt);
	}
	
	public String getNationalOt() {
		return getStr("national_ot");
	}

	public void setDutyCharge(String dutyCharge) {
		set("duty_charge", dutyCharge);
	}
	
	public String getDutyCharge() {
		return getStr("duty_charge");
	}

	public void setMidShifts(String midShifts) {
		set("mid_shifts", midShifts);
	}
	
	public String getMidShifts() {
		return getStr("mid_shifts");
	}

	public void setNightShifts(String nightShifts) {
		set("night_shifts", nightShifts);
	}
	
	public String getNightShifts() {
		return getStr("night_shifts");
	}

	public void setHightempAllowance(String hightempAllowance) {
		set("hightemp_allowance", hightempAllowance);
	}
	
	public String getHightempAllowance() {
		return getStr("hightemp_allowance");
	}

	public void setSeniorityAllowance(String seniorityAllowance) {
		set("seniority_allowance", seniorityAllowance);
	}
	
	public String getSeniorityAllowance() {
		return getStr("seniority_allowance");
	}

	public void setPartAllowance(String partAllowance) {
		set("part_allowance", partAllowance);
	}
	
	public String getPartAllowance() {
		return getStr("part_allowance");
	}

	public void setOtherAllowance(String otherAllowance) {
		set("other_allowance", otherAllowance);
	}
	
	public String getOtherAllowance() {
		return getStr("other_allowance");
	}

	public void setOtherAdjuest(String otherAdjuest) {
		set("other_adjuest", otherAdjuest);
	}
	
	public String getOtherAdjuest() {
		return getStr("other_adjuest");
	}

	public void setShouldWorkdays(String shouldWorkdays) {
		set("should_workdays", shouldWorkdays);
	}
	
	public String getShouldWorkdays() {
		return getStr("should_workdays");
	}

	public void setSickLeave(String sickLeave) {
		set("sick_leave", sickLeave);
	}
	
	public String getSickLeave() {
		return getStr("sick_leave");
	}

	public void setCasualLeave(String casualLeave) {
		set("casual_leave", casualLeave);
	}
	
	public String getCasualLeave() {
		return getStr("casual_leave");
	}

	public void setAbsenceDuty(String absenceDuty) {
		set("absence_duty", absenceDuty);
	}
	
	public String getAbsenceDuty() {
		return getStr("absence_duty");
	}

	public void setAbsentWork(String absentWork) {
		set("absent_work", absentWork);
	}
	
	public String getAbsentWork() {
		return getStr("absent_work");
	}

	public void setProbatDeduction(String probatDeduction) {
		set("probat_deduction", probatDeduction);
	}
	
	public String getProbatDeduction() {
		return getStr("probat_deduction");
	}

	public void setRewardPunish(String rewardPunish) {
		set("reward_punish", rewardPunish);
	}
	
	public String getRewardPunish() {
		return getStr("reward_punish");
	}

	public void setRestAnleave(String restAnleave) {
		set("rest_anleave", restAnleave);
	}
	
	public String getRestAnleave() {
		return getStr("rest_anleave");
	}

	public void setHireDate(String hireDate) {
		set("hire_date", hireDate);
	}
	
	public String getHireDate() {
		return getStr("hire_date");
	}

	public void setLeaveDate(String leaveDate) {
		set("leave_date", leaveDate);
	}
	
	public String getLeaveDate() {
		return getStr("leave_date");
	}

	public void setStatus(String status) {
		set("status", status);
	}
	
	public String getStatus() {
		return getStr("status");
	}

	public void setRemarks(String remarks) {
		set("remarks", remarks);
	}
	
	public String getRemarks() {
		return getStr("remarks");
	}

	public void setCreateUser(String createUser) {
		set("create_user", createUser);
	}
	
	public String getCreateUser() {
		return getStr("create_user");
	}

	public void setCreatTime(String creatTime) {
		set("creat_time", creatTime);
	}
	
	public String getCreatTime() {
		return getStr("creat_time");
	}

}
