package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXdLogsLeave<M extends BaseXdLogsLeave<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}
	
	public Long getId() {
		return getLong("id");
	}

	public void setSummaryId(String summaryId) {
		set("summary_id", summaryId);
	}
	
	public String getSummaryId() {
		return getStr("summary_id");
	}

	public void setType(String type) {
		set("type", type);
	}
	
	public String getType() {
		return getStr("type");
	}

	public void setOldValue(String oldValue) {
		set("old_value", oldValue);
	}
	
	public String getOldValue() {
		return getStr("old_value");
	}

	public void setNewValue(String newValue) {
		set("new_value", newValue);
	}
	
	public String getNewValue() {
		return getStr("new_value");
	}

	public void setCreateTime(String createTime) {
		set("create_time", createTime);
	}
	
	public String getCreateTime() {
		return getStr("create_time");
	}

	public void setCreateUser(String createUser) {
		set("create_user", createUser);
	}
	
	public String getCreateUser() {
		return getStr("create_user");
	}

}
