package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaAnswers<M extends BaseOaAnswers<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setTid(java.lang.String tid) {
		set("tid", tid);
	}
	
	public java.lang.String getTid() {
		return getStr("tid");
	}

	public void setQid(java.lang.String qid) {
		set("qid", qid);
	}
	
	public java.lang.String getQid() {
		return getStr("qid");
	}

	public void setCid(java.lang.String cid) {
		set("cid", cid);
	}
	
	public java.lang.String getCid() {
		return getStr("cid");
	}

	public void setCvalue(java.lang.String cvalue) {
		set("cvalue", cvalue);
	}
	
	public java.lang.String getCvalue() {
		return getStr("cvalue");
	}

	public void setScore(java.lang.String score) {
		set("score", score);
	}
	
	public java.lang.String getScore() {
		return getStr("score");
	}

	public void setCuser(java.lang.String cuser) {
		set("cuser", cuser);
	}
	
	public java.lang.String getCuser() {
		return getStr("cuser");
	}

	public void setCuserid(java.lang.String cuserid) {
		set("cuserid", cuserid);
	}
	
	public java.lang.String getCuserid() {
		return getStr("cuserid");
	}

	public void setCtime(java.lang.String ctime) {
		set("ctime", ctime);
	}
	
	public java.lang.String getCtime() {
		return getStr("ctime");
	}

	public void setCanswer(java.lang.String canswer) {
		set("canswer", canswer);
	}
	
	public java.lang.String getCanswer() {
		return getStr("canswer");
	}

}
