package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXdDayModel<M extends BaseXdDayModel<M>> extends Model<M> implements IBean {

	public void setId(String id) {
		set("id", id);
	}
	
	public String getId() {
		return getStr("id");
	}

	public void setDays(String days) {
		set("days", days);
	}
	
	public String getDays() {
		return getStr("days");
	}

	public void setWeeks(String weeks) {
		set("weeks", weeks);
	}
	
	public String getWeeks() {
		return getStr("weeks");
	}

	public void setHolidays(String holidays) {
		set("holidays", holidays);
	}
	
	public String getHolidays() {
		return getStr("holidays");
	}

	public void setStatus(String status) {
		set("status", status);
	}
	
	public String getStatus() {
		return getStr("status");
	}

	public void setCreateUser(String createUser) {
		set("create_user", createUser);
	}
	
	public String getCreateUser() {
		return getStr("create_user");
	}

	public void setCreateDate(String createDate) {
		set("create_date", createDate);
	}
	
	public String getCreateDate() {
		return getStr("create_date");
	}

}
