package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCrmCustomerVisit<M extends BaseCrmCustomerVisit<M>> extends Model<M> implements IBean {

	public void setId(String id) {
		set("id", id);
	}
	
	public String getId() {
		return getStr("id");
	}

	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}

	public java.lang.String getUserid() {
		return getStr("userid");
	}

	public void setCreateUserName(String createUserName) {
		set("create_user_name", createUserName);
	}
	
	public String getCreateUserName() {
		return getStr("create_user_name");
	}

	public void setOrgId(java.lang.String orgId) {
		set("org_id", orgId);
	}

	public java.lang.String getOrgId() {
		return getStr("org_id");
	}

	public void setOrgName(java.lang.String orgName) {
		set("org_name", orgName);
	}

	public java.lang.String getOrgName() {
		return getStr("org_name");
	}

	public void setCreateTime(String createTime) {
		set("create_time", createTime);
	}
	
	public String getCreateTime() {
		return getStr("create_time");
	}

	public void setIfSubmit(String ifSubmit) {
		set("if_submit", ifSubmit);
	}
	
	public String getIfSubmit() {
		return getStr("if_submit");
	}

	public void setIfComplete(String ifComplete) {
		set("if_complete", ifComplete);
	}
	
	public String getIfComplete() {
		return getStr("if_complete");
	}

	public void setIfAgree(String ifAgree) {
		set("if_agree", ifAgree);
	}
	
	public String getIfAgree() {
		return getStr("if_agree");
	}

	public void setProcInsId(String procInsId) {
		set("proc_ins_id", procInsId);
	}
	
	public String getProcInsId() {
		return getStr("proc_ins_id");
	}

	public void setVisitTime(String visitTime) {
		set("visit_time", visitTime);
	}
	
	public String getVisitTime() {
		return getStr("visit_time");
	}

	public void setCustomerId(String customerId) {
		set("customer_id", customerId);
	}
	
	public String getCustomerId() {
		return getStr("customer_id");
	}

	public void setCustomerName(String customerName) {
		set("customer_name", customerName);
	}
	
	public String getCustomerName() {
		return getStr("customer_name");
	}

	public void setCustomerCompanyId(String customerCompanyId) {
		set("customer_company_id", customerCompanyId);
	}
	
	public String getCustomerCompanyId() {
		return getStr("customer_company_id");
	}

	public void setCustomerCompanyName(String customerCompanyName) {
		set("customer_company_name", customerCompanyName);
	}
	
	public String getCustomerCompanyName() {
		return getStr("customer_company_name");
	}

	public void setVisitAddress(String visitAddress) {
		set("visit_address", visitAddress);
	}
	
	public String getVisitAddress() {
		return getStr("visit_address");
	}

	public void setVisitInfo(String visitInfo) {
		set("visit_info", visitInfo);
	}
	
	public String getVisitInfo() {
		return getStr("visit_info");
	}

	public void setServerUserName(String serverUserName) {
		set("server_user_name", serverUserName);
	}
	
	public String getServerUserName() {
		return getStr("server_user_name");
	}

	public void setServerType(String serverType) {
		set("server_type", serverType);
	}
	
	public String getServerType() {
		return getStr("server_type");
	}

	public void setDes(String des) {
		set("des", des);
	}
	
	public String getDes() {
		return getStr("des");
	}

	public void setNote1(String note1) {
		set("note1", note1);
	}
	
	public String getNote1() {
		return getStr("note1");
	}

	public void setNote2(String note2) {
		set("note2", note2);
	}
	
	public String getNote2() {
		return getStr("note2");
	}

	public void setNote3(String note3) {
		set("note3", note3);
	}
	
	public String getNote3() {
		return getStr("note3");
	}

}
