package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaLetter<M extends BaseOaLetter<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setNum(java.lang.String num) {
		set("num", num);
	}
	
	public java.lang.String getNum() {
		return getStr("num");
	}

	public void setFromtime(java.lang.String fromtime) {
		set("fromtime", fromtime);
	}
	
	public java.lang.String getFromtime() {
		return getStr("fromtime");
	}

	public void setFromer(java.lang.String fromer) {
		set("fromer", fromer);
	}
	
	public java.lang.String getFromer() {
		return getStr("fromer");
	}

	public void setContact(java.lang.String contact) {
		set("contact", contact);
	}
	
	public java.lang.String getContact() {
		return getStr("contact");
	}

	public void setFromunit(java.lang.String fromunit) {
		set("fromunit", fromunit);
	}
	
	public java.lang.String getFromunit() {
		return getStr("fromunit");
	}

	public void setFromnum(java.lang.String fromnum) {
		set("fromnum", fromnum);
	}
	
	public java.lang.String getFromnum() {
		return getStr("fromnum");
	}

	public void setLeadersid(java.lang.String leadersid) {
		set("leadersid", leadersid);
	}
	
	public java.lang.String getLeadersid() {
		return getStr("leadersid");
	}

	public void setLeadersname(java.lang.String leadersname) {
		set("leadersname", leadersname);
	}
	
	public java.lang.String getLeadersname() {
		return getStr("leadersname");
	}

	public void setLeadersremark(java.lang.String leadersremark) {
		set("leadersremark", leadersremark);
	}
	
	public java.lang.String getLeadersremark() {
		return getStr("leadersremark");
	}

	public void setDepartsid(java.lang.String departsid) {
		set("departsid", departsid);
	}
	
	public java.lang.String getDepartsid() {
		return getStr("departsid");
	}

	public void setDepartsname(java.lang.String departsname) {
		set("departsname", departsname);
	}
	
	public java.lang.String getDepartsname() {
		return getStr("departsname");
	}

	public void setSuggestions(java.lang.String suggestions) {
		set("suggestions", suggestions);
	}
	
	public java.lang.String getSuggestions() {
		return getStr("suggestions");
	}

	public void setContents(java.lang.String contents) {
		set("contents", contents);
	}
	
	public java.lang.String getContents() {
		return getStr("contents");
	}

	public void setRecontents(java.lang.String recontents) {
		set("recontents", recontents);
	}
	
	public java.lang.String getRecontents() {
		return getStr("recontents");
	}

	public void setShowtitle(java.lang.String showtitle) {
		set("showtitle", showtitle);
	}
	
	public java.lang.String getShowtitle() {
		return getStr("showtitle");
	}

	public void setShowcontents(java.lang.String showcontents) {
		set("showcontents", showcontents);
	}
	
	public java.lang.String getShowcontents() {
		return getStr("showcontents");
	}

	public void setShowrecontents(java.lang.String showrecontents) {
		set("showrecontents", showrecontents);
	}
	
	public java.lang.String getShowrecontents() {
		return getStr("showrecontents");
	}

	public void setCtime(java.lang.String ctime) {
		set("ctime", ctime);
	}
	
	public java.lang.String getCtime() {
		return getStr("ctime");
	}

	public void setCuserid(java.lang.String cuserid) {
		set("cuserid", cuserid);
	}
	
	public java.lang.String getCuserid() {
		return getStr("cuserid");
	}

	public void setCusername(java.lang.String cusername) {
		set("cusername", cusername);
	}
	
	public java.lang.String getCusername() {
		return getStr("cusername");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

	public void setNbshrids(java.lang.String nbshrids) {
		set("nbshrids", nbshrids);
	}
	
	public java.lang.String getNbshrids() {
		return getStr("nbshrids");
	}

	public void setNbshrnames(java.lang.String nbshrnames) {
		set("nbshrnames", nbshrnames);
	}
	
	public java.lang.String getNbshrnames() {
		return getStr("nbshrnames");
	}

	public void setNbshrremark(java.lang.String nbshrremark) {
		set("nbshrremark", nbshrremark);
	}
	
	public java.lang.String getNbshrremark() {
		return getStr("nbshrremark");
	}

	public void setCbrids(java.lang.String cbrids) {
		set("cbrids", cbrids);
	}
	
	public java.lang.String getCbrids() {
		return getStr("cbrids");
	}

	public void setCbrnames(java.lang.String cbrnames) {
		set("cbrnames", cbrnames);
	}
	
	public java.lang.String getCbrnames() {
		return getStr("cbrnames");
	}

	public void setCbrremark(java.lang.String cbrremark) {
		set("cbrremark", cbrremark);
	}
	
	public java.lang.String getCbrremark() {
		return getStr("cbrremark");
	}

	public void setKsldids(java.lang.String ksldids) {
		set("ksldids", ksldids);
	}
	
	public java.lang.String getKsldids() {
		return getStr("ksldids");
	}

	public void setKdldnames(java.lang.String kdldnames) {
		set("kdldnames", kdldnames);
	}
	
	public java.lang.String getKdldnames() {
		return getStr("kdldnames");
	}

	public void setClqx(java.lang.String clqx) {
		set("clqx", clqx);
	}
	
	public java.lang.String getClqx() {
		return getStr("clqx");
	}

	public void setCljsrq(java.lang.String cljsrq) {
		set("cljsrq", cljsrq);
	}
	
	public java.lang.String getCljsrq() {
		return getStr("cljsrq");
	}

	public void setSyts(java.lang.String syts) {
		set("syts", syts);
	}
	
	public java.lang.String getSyts() {
		return getStr("syts");
	}

	public void setLettertype(java.lang.String lettertype) {
		set("lettertype", lettertype);
	}
	
	public java.lang.String getLettertype() {
		return getStr("lettertype");
	}

	public void setFromchannel(java.lang.String fromchannel) {
		set("fromchannel", fromchannel);
	}
	
	public java.lang.String getFromchannel() {
		return getStr("fromchannel");
	}

	public void setLetterresult(java.lang.String letterresult) {
		set("letterresult", letterresult);
	}
	
	public java.lang.String getLetterresult() {
		return getStr("letterresult");
	}

	public void setLetterreason(java.lang.String letterreason) {
		set("letterreason", letterreason);
	}
	
	public java.lang.String getLetterreason() {
		return getStr("letterreason");
	}

	public void setPublicornot(java.lang.String publicornot) {
		set("publicornot", publicornot);
	}
	
	public java.lang.String getPublicornot() {
		return getStr("publicornot");
	}

	public void setFromersug(java.lang.String fromersug) {
		set("fromersug", fromersug);
	}
	
	public java.lang.String getFromersug() {
		return getStr("fromersug");
	}

	public void setKeywords(java.lang.String keywords) {
		set("keywords", keywords);
	}
	
	public java.lang.String getKeywords() {
		return getStr("keywords");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setBackup1(java.lang.String backup1) {
		set("backup1", backup1);
	}
	
	public java.lang.String getBackup1() {
		return getStr("backup1");
	}

	public void setBackup2(java.lang.String backup2) {
		set("backup2", backup2);
	}
	
	public java.lang.String getBackup2() {
		return getStr("backup2");
	}

	public void setBackup3(java.lang.String backup3) {
		set("backup3", backup3);
	}
	
	public java.lang.String getBackup3() {
		return getStr("backup3");
	}

	public void setHostsid(java.lang.String hostsid) {
		set("hostsid", hostsid);
	}
	
	public java.lang.String getHostsid() {
		return getStr("hostsid");
	}

	public void setHostsname(java.lang.String hostsname) {
		set("hostsname", hostsname);
	}
	
	public java.lang.String getHostsname() {
		return getStr("hostsname");
	}

	public void setCustomersid(java.lang.String customersid) {
		set("customersid", customersid);
	}
	
	public java.lang.String getCustomersid() {
		return getStr("customersid");
	}

	public void setCustomersname(java.lang.String customersname) {
		set("customersname", customersname);
	}
	
	public java.lang.String getCustomersname() {
		return getStr("customersname");
	}

}
