package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXdWorkExper<M extends BaseXdWorkExper<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return getInt("id");
	}

	public void setEid(Integer eid) {
		set("eid", eid);
	}

	public Integer getEid() {
		return getInt("eid");
	}

	public void setEntrydate(String entrydate) {
		set("entrydate", entrydate);
	}

	public String getEntrydate() {
		return getStr("entrydate");
	}

	public void setDepartdate(String departdate) {
		set("departdate", departdate);
	}

	public String getDepartdate() {
		return getStr("departdate");
	}

	public void setServiceunit(String serviceunit) {
		set("serviceunit", serviceunit);
	}

	public String getServiceunit() {
		return getStr("serviceunit");
	}

	public void setJob(String job) {
		set("job", job);
	}

	public String getJob() {
		return getStr("job");
	}

	public void setAddr(String addr) {
		set("addr", addr);
	}

	public String getAddr() {
		return getStr("addr");
	}

	public void setCtime(String ctime) {
		set("ctime", ctime);
	}

	public String getCtime() {
		return getStr("ctime");
	}

	public void setCuser(String cuser) {
		set("cuser", cuser);
	}

	public String getCuser() {
		return getStr("cuser");
	}

}
