package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXdRcpSummary<M extends BaseXdRcpSummary<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}
	
	public Long getId() {
		return getLong("id");
	}

	public void setDeptValue(String deptValue) {
		set("dept_value", deptValue);
	}
	
	public String getDeptValue() {
		return getStr("dept_value");
	}

	public void setDeptName(String deptName) {
		set("dept_name", deptName);
	}
	
	public String getDeptName() {
		return getStr("dept_name");
	}

	public void setUnitValue(String unitValue) {
		set("unit_value", unitValue);
	}
	
	public String getUnitValue() {
		return getStr("unit_value");
	}

	public void setUnitName(String unitName) {
		set("unit_name", unitName);
	}
	
	public String getUnitName() {
		return getStr("unit_name");
	}

	public void setProjectValue(String projectValue) {
		set("project_value", projectValue);
	}
	
	public String getProjectValue() {
		return getStr("project_value");
	}

	public void setProjectName(String projectName) {
		set("project_name", projectName);
	}
	
	public String getProjectName() {
		return getStr("project_name");
	}

	public void setEmpName(String empName) {
		set("emp_name", empName);
	}
	
	public String getEmpName() {
		return getStr("emp_name");
	}

	public void setIdnum(String idnum) {
		set("idnum", idnum);
	}
	
	public String getIdnum() {
		return getStr("idnum");
	}

	public void setWorStation(String worStation) {
		set("wor_station", worStation);
	}
	
	public String getWorStation() {
		return getStr("wor_station");
	}

	public void setShfitName(String shfitName) {
		set("shfit_name", shfitName);
	}
	
	public String getShfitName() {
		return getStr("shfit_name");
	}

	public void setWorkHours(String workHours) {
		set("work_hours", workHours);
	}
	
	public String getWorkHours() {
		return getStr("work_hours");
	}

	public void setRcpDays(String rcpDays) {
		set("rcp_days", rcpDays);
	}
	
	public String getRcpDays() {
		return getStr("rcp_days");
	}

	public void setWorkDays(String workDays) {
		set("work_days", workDays);
	}
	
	public String getWorkDays() {
		return getStr("work_days");
	}

	public void setRcpStandard(String rcpStandard) {
		set("rcp_standard", rcpStandard);
	}
	
	public String getRcpStandard() {
		return getStr("rcp_standard");
	}

	public void setRental(String rental) {
		set("rental", rental);
	}
	
	public String getRental() {
		return getStr("rental");
	}

	public void setRemarks(String remarks) {
		set("remarks", remarks);
	}
	
	public String getRemarks() {
		return getStr("remarks");
	}

	public void setRcpYear(String rcpYear) {
		set("rcp_year", rcpYear);
	}
	
	public String getRcpYear() {
		return getStr("rcp_year");
	}

	public void setRcpMonth(String rcpMonth) {
		set("rcp_month", rcpMonth);
	}
	
	public String getRcpMonth() {
		return getStr("rcp_month");
	}

	public void setRcpMonthYear(String rcpMonthYear) {
		set("rcp_month_year", rcpMonthYear);
	}
	
	public String getRcpMonthYear() {
		return getStr("rcp_month_year");
	}

	public void setStatus(String status) {
		set("status", status);
	}
	
	public String getStatus() {
		return getStr("status");
	}

	public void setCreateUser(String createUser) {
		set("create_user", createUser);
	}
	
	public String getCreateUser() {
		return getStr("create_user");
	}

	public void setCreateDate(String createDate) {
		set("create_date", createDate);
	}
	
	public String getCreateDate() {
		return getStr("create_date");
	}

}
