package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaDocuments<M extends BaseOaDocuments<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setDocumentname(java.lang.String documentname) {
		set("documentname", documentname);
	}
	
	public java.lang.String getDocumentname() {
		return getStr("documentname");
	}

	public void setKeywords(java.lang.String keywords) {
		set("keywords", keywords);
	}
	
	public java.lang.String getKeywords() {
		return getStr("keywords");
	}

	public void setCuserid(java.lang.String cuserid) {
		set("cuserid", cuserid);
	}
	
	public java.lang.String getCuserid() {
		return getStr("cuserid");
	}

	public void setCreatedate(java.lang.String createdate) {
		set("createdate", createdate);
	}
	
	public java.lang.String getCreatedate() {
		return getStr("createdate");
	}

	public void setCusername(java.lang.String cusername) {
		set("cusername", cusername);
	}
	
	public java.lang.String getCusername() {
		return getStr("cusername");
	}

	public void setDepartments(java.lang.String departments) {
		set("departments", departments);
	}
	
	public java.lang.String getDepartments() {
		return getStr("departments");
	}

	public void setBackup1(java.lang.String backup1) {
		set("backup1", backup1);
	}
	
	public java.lang.String getBackup1() {
		return getStr("backup1");
	}

	public void setBackup2(java.lang.String backup2) {
		set("backup2", backup2);
	}
	
	public java.lang.String getBackup2() {
		return getStr("backup2");
	}

	public void setBackup3(java.lang.String backup3) {
		set("backup3", backup3);
	}
	
	public java.lang.String getBackup3() {
		return getStr("backup3");
	}

}
