package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXdOplogSummary<M extends BaseXdOplogSummary<M>> extends Model<M> implements IBean {

	public void setId(String id) {
		set("id", id);
	}
	
	public String getId() {
		return getStr("id");
	}

	public void setOid(String oid) {
		set("oid", oid);
	}
	
	public String getOid() {
		return getStr("oid");
	}

	public void setTid(String tid) {
		set("tid", tid);
	}
	
	public String getTid() {
		return getStr("tid");
	}

	public void setTname(String tname) {
		set("tname", tname);
	}
	
	public String getTname() {
		return getStr("tname");
	}

	public void setChangeb(String changeb) {
		set("changeb", changeb);
	}
	
	public String getChangeb() {
		return getStr("changeb");
	}

	public void setChangea(String changea) {
		set("changea", changea);
	}
	
	public String getChangea() {
		return getStr("changea");
	}

	public void setOtype(String otype) {
		set("otype", otype);
	}
	
	public String getOtype() {
		return getStr("otype");
	}

	public void setStatus(String status) {
		set("status", status);
	}
	
	public String getStatus() {
		return getStr("status");
	}

	public void setCuser(String cuser) {
		set("cuser", cuser);
	}
	
	public String getCuser() {
		return getStr("cuser");
	}

	public void setCtime(String ctime) {
		set("ctime", ctime);
	}
	
	public String getCtime() {
		return getStr("ctime");
	}

}
