package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaWorkPlan<M extends BaseOaWorkPlan<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setStart(java.lang.String start) {
		set("start", start);
	}
	
	public java.lang.String getStart() {
		return getStr("start");
	}

	public void setEnd(java.lang.String end) {
		set("end", end);
	}
	
	public java.lang.String getEnd() {
		return getStr("end");
	}

	public void setCuer(java.lang.String cuer) {
		set("cuer", cuer);
	}
	
	public java.lang.String getCuer() {
		return getStr("cuer");
	}

	public void setCdate(java.lang.String cdate) {
		set("cdate", cdate);
	}
	
	public java.lang.String getCdate() {
		return getStr("cdate");
	}

}
