package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXdEffict<M extends BaseXdEffict<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	public void setEid(String eid) {
		set("eid", eid);
	}
	
	public String getEid() {
		return getStr("eid");
	}

	public void setValues(String values) {
		set("values", values);
	}
	
	public String getValues() {
		return getStr("values");
	}

	public void setEffectDate(String effectDate) {
		set("effectDate", effectDate);
	}
	
	public String getEffectDate() {
		return getStr("effectDate");
	}

	public void setFieldtype(Integer fieldtype) {
		set("fieldtype", fieldtype);
	}
	
	public Integer getFieldtype() {
		return getInt("fieldtype");
	}

	public void setStatus(String status) {
		set("status", status);
	}
	
	public String getStatus() {
		return getStr("status");
	}

	public void setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
	}

	public java.lang.String getRemarks() {
		return getStr("remarks");
	}
	public void setCuser(String cuser) {
		set("cuser", cuser);
	}
	
	public String getCuser() {
		return getStr("cuser");
	}

	public void setCtime(String ctime) {
		set("ctime", ctime);
	}
	
	public String getCtime() {
		return getStr("ctime");
	}

	public void setUuser(String uuser) {
		set("uuser", uuser);
	}
	
	public String getUuser() {
		return getStr("uuser");
	}

	public void setUtime(String utime) {
		set("utime", utime);
	}
	
	public String getUtime() {
		return getStr("utime");
	}

	public void setOveruser(String overuser) {
		set("overuser", overuser);
	}
	
	public String getOveruser() {
		return getStr("overuser");
	}

	public void setOvertime(String overtime) {
		set("overtime", overtime);
	}
	
	public String getOvertime() {
		return getStr("overtime");
	}

	public void setBackup1(String backup1) {
		set("backup1", backup1);
	}
	
	public String getBackup1() {
		return getStr("backup1");
	}

	public void setBackup2(String backup2) {
		set("backup2", backup2);
	}
	
	public String getBackup2() {
		return getStr("backup2");
	}

	public void setBackup3(String backup3) {
		set("backup3", backup3);
	}
	
	public String getBackup3() {
		return getStr("backup3");
	}

}
