package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXdScheduleSummary<M extends BaseXdScheduleSummary<M>> extends Model<M> implements IBean {

	public void setId(String id) {
		set("id", id);
	}
	
	public String getId() {
		return getStr("id");
	}

	public void setDeptValue(String deptValue) {
		set("dept_value", deptValue);
	}
	
	public String getDeptValue() {
		return getStr("dept_value");
	}

	public void setDeptName(String deptName) {
		set("dept_name", deptName);
	}
	
	public String getDeptName() {
		return getStr("dept_name");
	}

	public void setUnitValue(String unitValue) {
		set("unit_value", unitValue);
	}
	
	public String getUnitValue() {
		return getStr("unit_value");
	}

	public void setUnitName(String unitName) {
		set("unit_name", unitName);
	}
	
	public String getUnitName() {
		return getStr("unit_name");
	}

	public void setProjectValue(String projectValue) {
		set("project_value", projectValue);
	}
	
	public String getProjectValue() {
		return getStr("project_value");
	}

	public void setProjectName(String projectName) {
		set("project_name", projectName);
	}
	
	public String getProjectName() {
		return getStr("project_name");
	}

	public void setEmpNum(String empNum) {
		set("emp_num", empNum);
	}
	
	public String getEmpNum() {
		return getStr("emp_num");
	}

	public void setEmpId(String empId) {
		set("emp_id", empId);
	}
	
	public String getEmpId() {
		return getStr("emp_id");
	}

	public void setEmpName(String empName) {
		set("emp_name", empName);
	}
	
	public String getEmpName() {
		return getStr("emp_name");
	}

	public void setWorkStation(String workStation) {
		set("work_station", workStation);
	}
	
	public String getWorkStation() {
		return getStr("work_station");
	}

	public void setScheduleYear(String scheduleYear) {
		set("schedule_year", scheduleYear);
	}
	
	public String getScheduleYear() {
		return getStr("schedule_year");
	}

	public void setScheduleMonth(String scheduleMonth) {
		set("schedule_month", scheduleMonth);
	}
	
	public String getScheduleMonth() {
		return getStr("schedule_month");
	}

	public void setScheduleYearMonth(String scheduleYearMonth) {
		set("schedule_year_month", scheduleYearMonth);
	}
	
	public String getScheduleYearMonth() {
		return getStr("schedule_year_month");
	}

	public void setDay00(String day00) {
		set("day00", day00);
	}
	
	public String getDay00() {
		return getStr("day00");
	}

	public void setDay01(String day01) {
		set("day01", day01);
	}
	
	public String getDay01() {
		return getStr("day01");
	}

	public void setDay02(String day02) {
		set("day02", day02);
	}
	
	public String getDay02() {
		return getStr("day02");
	}

	public void setDay03(String day03) {
		set("day03", day03);
	}
	
	public String getDay03() {
		return getStr("day03");
	}

	public void setDay04(String day04) {
		set("day04", day04);
	}
	
	public String getDay04() {
		return getStr("day04");
	}

	public void setDay05(String day05) {
		set("day05", day05);
	}
	
	public String getDay05() {
		return getStr("day05");
	}

	public void setDay06(String day06) {
		set("day06", day06);
	}
	
	public String getDay06() {
		return getStr("day06");
	}

	public void setDay07(String day07) {
		set("day07", day07);
	}
	
	public String getDay07() {
		return getStr("day07");
	}

	public void setDay08(String day08) {
		set("day08", day08);
	}
	
	public String getDay08() {
		return getStr("day08");
	}

	public void setDay09(String day09) {
		set("day09", day09);
	}
	
	public String getDay09() {
		return getStr("day09");
	}

	public void setDay10(String day10) {
		set("day10", day10);
	}
	
	public String getDay10() {
		return getStr("day10");
	}

	public void setDay11(String day11) {
		set("day11", day11);
	}
	
	public String getDay11() {
		return getStr("day11");
	}

	public void setDay12(String day12) {
		set("day12", day12);
	}
	
	public String getDay12() {
		return getStr("day12");
	}

	public void setDay13(String day13) {
		set("day13", day13);
	}
	
	public String getDay13() {
		return getStr("day13");
	}

	public void setDay14(String day14) {
		set("day14", day14);
	}
	
	public String getDay14() {
		return getStr("day14");
	}

	public void setDay15(String day15) {
		set("day15", day15);
	}
	
	public String getDay15() {
		return getStr("day15");
	}

	public void setDay16(String day16) {
		set("day16", day16);
	}
	
	public String getDay16() {
		return getStr("day16");
	}

	public void setDay17(String day17) {
		set("day17", day17);
	}
	
	public String getDay17() {
		return getStr("day17");
	}

	public void setDay18(String day18) {
		set("day18", day18);
	}
	
	public String getDay18() {
		return getStr("day18");
	}

	public void setDay19(String day19) {
		set("day19", day19);
	}
	
	public String getDay19() {
		return getStr("day19");
	}

	public void setDay20(String day20) {
		set("day20", day20);
	}
	
	public String getDay20() {
		return getStr("day20");
	}

	public void setDay21(String day21) {
		set("day21", day21);
	}
	
	public String getDay21() {
		return getStr("day21");
	}

	public void setDay22(String day22) {
		set("day22", day22);
	}
	
	public String getDay22() {
		return getStr("day22");
	}

	public void setDay23(String day23) {
		set("day23", day23);
	}
	
	public String getDay23() {
		return getStr("day23");
	}

	public void setDay24(String day24) {
		set("day24", day24);
	}
	
	public String getDay24() {
		return getStr("day24");
	}

	public void setDay25(String day25) {
		set("day25", day25);
	}
	
	public String getDay25() {
		return getStr("day25");
	}

	public void setDay26(String day26) {
		set("day26", day26);
	}
	
	public String getDay26() {
		return getStr("day26");
	}

	public void setDay27(String day27) {
		set("day27", day27);
	}
	
	public String getDay27() {
		return getStr("day27");
	}

	public void setDay28(String day28) {
		set("day28", day28);
	}
	
	public String getDay28() {
		return getStr("day28");
	}

	public void setDay29(String day29) {
		set("day29", day29);
	}
	
	public String getDay29() {
		return getStr("day29");
	}

	public void setDay30(String day30) {
		set("day30", day30);
	}
	
	public String getDay30() {
		return getStr("day30");
	}

	public void setDay31(String day31) {
		set("day31", day31);
	}
	
	public String getDay31() {
		return getStr("day31");
	}

	public void setOthours(Double othours) {
		set("othours", othours);
	}
	
	public Double getOthours() {
		return getDouble("othours");
	}

	public void setCurMonHours(Double curMonHours) {
		set("cur_mon_hours", curMonHours);
	}
	
	public Double getCurMonHours() {
		return getDouble("cur_mon_hours");
	}

	public void setFlags(String flags) {
		set("flags", flags);
	}
	
	public String getFlags() {
		return getStr("flags");
	}

	public void setRemarks(String remarks) {
		set("remarks", remarks);
	}
	
	public String getRemarks() {
		return getStr("remarks");
	}

	public void setStatus(String status) {
		set("status", status);
	}
	
	public String getStatus() {
		return getStr("status");
	}

	public void setCreateUser(String createUser) {
		set("create_user", createUser);
	}
	
	public String getCreateUser() {
		return getStr("create_user");
	}

	public void setCreateDate(String createDate) {
		set("create_date", createDate);
	}
	
	public String getCreateDate() {
		return getStr("create_date");
	}

	public void setUpdateUser(String updateUser) {
		set("update_user", updateUser);
	}
	
	public String getUpdateUser() {
		return getStr("update_user");
	}

	public void setUpdateDate(String updateDate) {
		set("update_date", updateDate);
	}
	
	public String getUpdateDate() {
		return getStr("update_date");
	}

}
