package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXdOplogDetail<M extends BaseXdOplogDetail<M>> extends Model<M> implements IBean {

	public void setId(String id) {
		set("id", id);
	}
	
	public String getId() {
		return getStr("id");
	}

	public void setRsid(String rsid) {
		set("rsid", rsid);
	}
	
	public String getRsid() {
		return getStr("rsid");
	}

	public void setFieldName(String fieldName) {
		set("fieldName", fieldName);
	}
	
	public String getFieldName() {
		return getStr("fieldName");
	}

	public void setFieldDesc(String fieldDesc) {
		set("fieldDesc", fieldDesc);
	}
	
	public String getFieldDesc() {
		return getStr("fieldDesc");
	}

	public void setOldValue(String oldValue) {
		set("oldValue", oldValue);
	}
	
	public String getOldValue() {
		return getStr("oldValue");
	}

	public void setNewValue(String newValue) {
		set("newValue", newValue);
	}
	
	public String getNewValue() {
		return getStr("newValue");
	}

}
