package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaPicNews<M extends BaseOaPicNews<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setDesc(java.lang.String desc) {
		set("desc", desc);
	}
	
	public java.lang.String getDesc() {
		return getStr("desc");
	}

	public void setImgurl(java.lang.String imgurl) {
		set("imgurl", imgurl);
	}
	
	public java.lang.String getImgurl() {
		return getStr("imgurl");
	}

	public void setIfshow(java.lang.String ifshow) {
		set("ifshow", ifshow);
	}
	
	public java.lang.String getIfshow() {
		return getStr("ifshow");
	}

	public void setRq(java.lang.String rq) {
		set("rq", rq);
	}
	
	public java.lang.String getRq() {
		return getStr("rq");
	}

	public void setCuser(java.lang.String cuser) {
		set("cuser", cuser);
	}
	
	public java.lang.String getCuser() {
		return getStr("cuser");
	}

	public void setCdate(java.lang.String cdate) {
		set("cdate", cdate);
	}
	
	public java.lang.String getCdate() {
		return getStr("cdate");
	}

	public void setBackup1(java.lang.String backup1) {
		set("backup1", backup1);
	}
	
	public java.lang.String getBackup1() {
		return getStr("backup1");
	}

	public void setBackup2(java.lang.String backup2) {
		set("backup2", backup2);
	}
	
	public java.lang.String getBackup2() {
		return getStr("backup2");
	}

}
