package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaShowinfo<M extends BaseOaShowinfo<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setMenuid(java.lang.String menuid) {
		set("menuid", menuid);
	}
	
	public java.lang.String getMenuid() {
		return getStr("menuid");
	}

	public void setPageid(java.lang.String pageid) {
		set("pageid", pageid);
	}
	
	public java.lang.String getPageid() {
		return getStr("pageid");
	}

	public void setShowpageinfotype(java.lang.String showpageinfotype) {
		set("showpageinfotype", showpageinfotype);
	}
	
	public java.lang.String getShowpageinfotype() {
		return getStr("showpageinfotype");
	}

	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}
	
	public java.lang.String getUserid() {
		return getStr("userid");
	}

	public void setInfotitle(java.lang.String infotitle) {
		set("infotitle", infotitle);
	}
	
	public java.lang.String getInfotitle() {
		return getStr("infotitle");
	}

	public void setInfocontenttext(java.lang.String infocontenttext) {
		set("infocontenttext", infocontenttext);
	}
	
	public java.lang.String getInfocontenttext() {
		return getStr("infocontenttext");
	}

	public void setInfocontent(java.lang.String infocontent) {
		set("infocontent", infocontent);
	}
	
	public java.lang.String getInfocontent() {
		return getStr("infocontent");
	}

	public void setOpuser(java.lang.String opuser) {
		set("opuser", opuser);
	}
	
	public java.lang.String getOpuser() {
		return getStr("opuser");
	}

	public void setChangetime(java.lang.String changetime) {
		set("changetime", changetime);
	}
	
	public java.lang.String getChangetime() {
		return getStr("changetime");
	}

	public void setViewcount(java.lang.Integer viewcount) {
		set("viewcount", viewcount);
	}
	
	public java.lang.Integer getViewcount() {
		return getInt("viewcount");
	}

	public void setSfshowhomepage(java.lang.String sfshowhomepage) {
		set("sfshowhomepage", sfshowhomepage);
	}
	
	public java.lang.String getSfshowhomepage() {
		return getStr("sfshowhomepage");
	}

	public void setSfpublish(java.lang.String sfpublish) {
		set("sfpublish", sfpublish);
	}
	
	public java.lang.String getSfpublish() {
		return getStr("sfpublish");
	}

	public void setPublisher(java.lang.String publisher) {
		set("publisher", publisher);
	}
	
	public java.lang.String getPublisher() {
		return getStr("publisher");
	}

	public void setPublisherid(java.lang.String publisherid) {
		set("publisherid", publisherid);
	}
	
	public java.lang.String getPublisherid() {
		return getStr("publisherid");
	}

	public void setPublishdatetime(java.lang.String publishdatetime) {
		set("publishdatetime", publishdatetime);
	}
	
	public java.lang.String getPublishdatetime() {
		return getStr("publishdatetime");
	}

	public void setAffairstype(java.lang.String affairstype) {
		set("affairstype", affairstype);
	}
	
	public java.lang.String getAffairstype() {
		return getStr("affairstype");
	}

	public void setShowhomepageimageurl(java.lang.String showhomepageimageurl) {
		set("showhomepageimageurl", showhomepageimageurl);
	}
	
	public java.lang.String getShowhomepageimageurl() {
		return getStr("showhomepageimageurl");
	}

	public void setAuthor(java.lang.String author) {
		set("author", author);
	}
	
	public java.lang.String getAuthor() {
		return getStr("author");
	}

	public void setReadid(java.lang.String readid) {
		set("readid", readid);
	}
	
	public java.lang.String getReadid() {
		return getStr("readid");
	}

	public void setZc(java.lang.String zc) {
		set("zc", zc);
	}
	
	public java.lang.String getZc() {
		return getStr("zc");
	}

	public void setBzc(java.lang.String bzc) {
		set("bzc", bzc);
	}
	
	public java.lang.String getBzc() {
		return getStr("bzc");
	}

	public void setTpksrq(java.lang.String tpksrq) {
		set("tpksrq", tpksrq);
	}
	
	public java.lang.String getTpksrq() {
		return getStr("tpksrq");
	}

	public void setTpjzrq(java.lang.String tpjzrq) {
		set("tpjzrq", tpjzrq);
	}
	
	public java.lang.String getTpjzrq() {
		return getStr("tpjzrq");
	}

}
