package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXdAnleaveSummary<M extends BaseXdAnleaveSummary<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}
	
	public Long getId() {
		return getLong("id");
	}

	public void setEmpId(String empId) {
		set("emp_id", empId);
	}
	
	public String getEmpId() {
		return getStr("emp_id");
	}

	public void setEmpName(String empName) {
		set("emp_name", empName);
	}
	
	public String getEmpName() {
		return getStr("emp_name");
	}

	public void setEmpNum(String empNum) {
		set("emp_num", empNum);
	}
	
	public String getEmpNum() {
		return getStr("emp_num");
	}

	public void setDeptId(String deptId) {
		set("dept_id", deptId);
	}
	
	public String getDeptId() {
		return getStr("dept_id");
	}

	public void setDeptName(String deptName) {
		set("dept_name", deptName);
	}
	
	public String getDeptName() {
		return getStr("dept_name");
	}

	public void setProjectValue(String projectValue) {
		set("project_value", projectValue);
	}
	
	public String getProjectValue() {
		return getStr("project_value");
	}

	public void setProjectName(String projectName) {
		set("project_name", projectName);
	}
	
	public String getProjectName() {
		return getStr("project_name");
	}

	public void setIdnum(String idnum) {
		set("idnum", idnum);
	}
	
	public String getIdnum() {
		return getStr("idnum");
	}

	public void setEmpRelation(String empRelation) {
		set("emp_relation", empRelation);
	}
	
	public String getEmpRelation() {
		return getStr("emp_relation");
	}

	public void setHireDate(String hireDate) {
		set("hire_date", hireDate);
	}
	
	public String getHireDate() {
		return getStr("hire_date");
	}

	public void setYear(String year) {
		set("year", year);
	}
	
	public String getYear() {
		return getStr("year");
	}

	public void setLeaveDays(String leaveDays) {
		set("leave_days", leaveDays);
	}
	
	public String getLeaveDays() {
		return getStr("leave_days");
	}

	public void setSurplusDays(String surplusDays) {
		set("surplus_days", surplusDays);
	}
	
	public String getSurplusDays() {
		return getStr("surplus_days");
	}

	public void setStatus(String status) {
		set("status", status);
	}
	
	public String getStatus() {
		return getStr("status");
	}

	public void setCreateUser(String createUser) {
		set("create_user", createUser);
	}
	
	public String getCreateUser() {
		return getStr("create_user");
	}

	public void setCreateDate(String createDate) {
		set("create_date", createDate);
	}
	
	public String getCreateDate() {
		return getStr("create_date");
	}

	public void setMonth1(Double month1) {
		set("month1", month1);
	}
	
	public Double getMonth1() {
		return getDouble("month1");
	}

	public void setMonth2(Double month2) {
		set("month2", month2);
	}
	
	public Double getMonth2() {
		return getDouble("month2");
	}

	public void setMonth3(Double month3) {
		set("month3", month3);
	}
	
	public Double getMonth3() {
		return getDouble("month3");
	}

	public void setMonth4(Double month4) {
		set("month4", month4);
	}
	
	public Double getMonth4() {
		return getDouble("month4");
	}

	public void setMonth5(Double month5) {
		set("month5", month5);
	}
	
	public Double getMonth5() {
		return getDouble("month5");
	}

	public void setMonth6(Double month6) {
		set("month6", month6);
	}
	
	public Double getMonth6() {
		return getDouble("month6");
	}

	public void setMonth7(Double month7) {
		set("month7", month7);
	}
	
	public Double getMonth7() {
		return getDouble("month7");
	}

	public void setMonth8(Double month8) {
		set("month8", month8);
	}
	
	public Double getMonth8() {
		return getDouble("month8");
	}

	public void setMonth9(Double month9) {
		set("month9", month9);
	}
	
	public Double getMonth9() {
		return getDouble("month9");
	}

	public void setMonth10(Double month10) {
		set("month10", month10);
	}
	
	public Double getMonth10() {
		return getDouble("month10");
	}

	public void setMonth11(Double month11) {
		set("month11", month11);
	}
	
	public Double getMonth11() {
		return getDouble("month11");
	}

	public void setMonth12(Double month12) {
		set("month12", month12);
	}
	
	public Double getMonth12() {
		return getDouble("month12");
	}

	public void setSum(Double sum) {
		set("sum", sum);
	}
	
	public Double getSum() {
		return getDouble("sum");
	}

	public void setRemarks(String remarks) {
		set("remarks", remarks);
	}
	
	public String getRemarks() {
		return getStr("remarks");
	}

	public void setDepartime(String departime) {
		set("departime", departime);
	}
	
	public String getDepartime() {
		return getStr("departime");
	}

}
