package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXdAnleaveSummary<M extends BaseXdAnleaveSummary<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}
	
	public Long getId() {
		return getLong("id");
	}

	public void setEmpId(String empId) {
		set("emp_id", empId);
	}
	
	public String getEmpId() {
		return getStr("emp_id");
	}

	public void setEmpName(String empName) {
		set("emp_name", empName);
	}
	
	public String getEmpName() {
		return getStr("emp_name");
	}

	public void setEmpNum(String empNum) {
		set("emp_num", empNum);
	}
	
	public String getEmpNum() {
		return getStr("emp_num");
	}

	public void setDeptId(String deptId) {
		set("dept_id", deptId);
	}
	
	public String getDeptId() {
		return getStr("dept_id");
	}

	public void setDeptName(String deptName) {
		set("dept_name", deptName);
	}
	
	public String getDeptName() {
		return getStr("dept_name");
	}

	public void setYear(String year) {
		set("year", year);
	}
	
	public String getYear() {
		return getStr("year");
	}

	public void setLeaveDays(String leaveDays) {
		set("leave_days", leaveDays);
	}
	
	public String getLeaveDays() {
		return getStr("leave_days");
	}

	public void setSurplusDays(String surplusDays) {
		set("surplus_days", surplusDays);
	}
	
	public String getSurplusDays() {
		return getStr("surplus_days");
	}

	public void setStatus(String status) {
		set("status", status);
	}
	
	public String getStatus() {
		return getStr("status");
	}

	public void setCreateUser(String createUser) {
		set("create_user", createUser);
	}
	
	public String getCreateUser() {
		return getStr("create_user");
	}

	public void setCreateDate(String createDate) {
		set("create_date", createDate);
	}
	
	public String getCreateDate() {
		return getStr("create_date");
	}

}
