package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXdTotalOnlineShifts<M extends BaseXdTotalOnlineShifts<M>> extends Model<M> implements IBean {

	public void setId(String id) {
		set("id", id);
	}
	
	public String getId() {
		return getStr("id");
	}

	public void setDeptName(String deptName) {
		set("dept_name", deptName);
	}
	
	public String getDeptName() {
		return getStr("dept_name");
	}

	public void setProjectName(String projectName) {
		set("project_name", projectName);
	}
	
	public String getProjectName() {
		return getStr("project_name");
	}

	public void setShifts1(String shifts1) {
		set("shifts1", shifts1);
	}
	
	public String getShifts1() {
		return getStr("shifts1");
	}

	public void setShifts2(String shifts2) {
		set("shifts2", shifts2);
	}
	
	public String getShifts2() {
		return getStr("shifts2");
	}

	public void setShifts3(String shifts3) {
		set("shifts3", shifts3);
	}
	
	public String getShifts3() {
		return getStr("shifts3");
	}

	public void setShifts4(String shifts4) {
		set("shifts4", shifts4);
	}
	
	public String getShifts4() {
		return getStr("shifts4");
	}

	public void setShifts5(String shifts5) {
		set("shifts5", shifts5);
	}
	
	public String getShifts5() {
		return getStr("shifts5");
	}

	public void setShifts6(String shifts6) {
		set("shifts6", shifts6);
	}
	
	public String getShifts6() {
		return getStr("shifts6");
	}

	public void setShifts7(String shifts7) {
		set("shifts7", shifts7);
	}
	
	public String getShifts7() {
		return getStr("shifts7");
	}

	public void setShifts8(String shifts8) {
		set("shifts8", shifts8);
	}
	
	public String getShifts8() {
		return getStr("shifts8");
	}

	public void setShifts9(String shifts9) {
		set("shifts9", shifts9);
	}
	
	public String getShifts9() {
		return getStr("shifts9");
	}

	public void setShifts10(String shifts10) {
		set("shifts10", shifts10);
	}
	
	public String getShifts10() {
		return getStr("shifts10");
	}

	public void setShifts11(String shifts11) {
		set("shifts11", shifts11);
	}
	
	public String getShifts11() {
		return getStr("shifts11");
	}

	public void setShifts12(String shifts12) {
		set("shifts12", shifts12);
	}
	
	public String getShifts12() {
		return getStr("shifts12");
	}

	public void setShifts13(String shifts13) {
		set("shifts13", shifts13);
	}
	
	public String getShifts13() {
		return getStr("shifts13");
	}

	public void setShifts14(String shifts14) {
		set("shifts14", shifts14);
	}
	
	public String getShifts14() {
		return getStr("shifts14");
	}

	public void setShifts15(String shifts15) {
		set("shifts15", shifts15);
	}
	
	public String getShifts15() {
		return getStr("shifts15");
	}

	public void setShifts16(String shifts16) {
		set("shifts16", shifts16);
	}
	
	public String getShifts16() {
		return getStr("shifts16");
	}

	public void setShifts17(String shifts17) {
		set("shifts17", shifts17);
	}
	
	public String getShifts17() {
		return getStr("shifts17");
	}

	public void setShifts18(String shifts18) {
		set("shifts18", shifts18);
	}
	
	public String getShifts18() {
		return getStr("shifts18");
	}

	public void setShifts19(String shifts19) {
		set("shifts19", shifts19);
	}
	
	public String getShifts19() {
		return getStr("shifts19");
	}

	public void setShifts20(String shifts20) {
		set("shifts20", shifts20);
	}
	
	public String getShifts20() {
		return getStr("shifts20");
	}

	public void setShifts21(String shifts21) {
		set("shifts21", shifts21);
	}
	
	public String getShifts21() {
		return getStr("shifts21");
	}

	public void setShifts22(String shifts22) {
		set("shifts22", shifts22);
	}
	
	public String getShifts22() {
		return getStr("shifts22");
	}

	public void setShifts23(String shifts23) {
		set("shifts23", shifts23);
	}
	
	public String getShifts23() {
		return getStr("shifts23");
	}

	public void setShifts24(String shifts24) {
		set("shifts24", shifts24);
	}
	
	public String getShifts24() {
		return getStr("shifts24");
	}

	public void setShifts25(String shifts25) {
		set("shifts25", shifts25);
	}
	
	public String getShifts25() {
		return getStr("shifts25");
	}

}
