package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXdSteps<M extends BaseXdSteps<M>> extends Model<M> implements IBean {

	public void setId(String id) {
		set("id", id);
	}
	
	public String getId() {
		return getStr("id");
	}

	public void setOid(String oid) {
		set("oid", oid);
	}
	
	public String getOid() {
		return getStr("oid");
	}

	public void setStype(String stype) {
		set("stype", stype);
	}
	
	public String getStype() {
		return getStr("stype");
	}

	public void setStep(String step) {
		set("step", step);
	}
	
	public String getStep() {
		return getStr("step");
	}

	public void setStepdesc(String stepdesc) {
		set("stepdesc", stepdesc);
	}
	
	public String getStepdesc() {
		return getStr("stepdesc");
	}

	public void setUserid(String userid) {
		set("userid", userid);
	}
	
	public String getUserid() {
		return getStr("userid");
	}

	public void setUsername(String username) {
		set("username", username);
	}
	
	public String getUsername() {
		return getStr("username");
	}

	public void setOrgid(String orgid) {
		set("orgid", orgid);
	}
	
	public String getOrgid() {
		return getStr("orgid");
	}

	public void setOrgname(String orgname) {
		set("orgname", orgname);
	}
	
	public String getOrgname() {
		return getStr("orgname");
	}

	public void setRemarks(String remarks) {
		set("remarks", remarks);
	}
	
	public String getRemarks() {
		return getStr("remarks");
	}

	public void setParentid(String parentid) {
		set("parentid", parentid);
	}
	
	public String getParentid() {
		return getStr("parentid");
	}

	public void setFinished(String finished) {
		set("finished", finished);
	}
	
	public String getFinished() {
		return getStr("finished");
	}

	public void setFinishtime(String finishtime) {
		set("finishtime", finishtime);
	}
	
	public String getFinishtime() {
		return getStr("finishtime");
	}

	public void setCuserid(String cuserid) {
		set("cuserid", cuserid);
	}
	
	public String getCuserid() {
		return getStr("cuserid");
	}

	public void setCusername(String cusername) {
		set("cusername", cusername);
	}
	
	public String getCusername() {
		return getStr("cusername");
	}

	public void setCtime(String ctime) {
		set("ctime", ctime);
	}
	
	public String getCtime() {
		return getStr("ctime");
	}

	public void setBackup1(String backup1) {
		set("backup1", backup1);
	}
	
	public String getBackup1() {
		return getStr("backup1");
	}

	public void setBackup2(String backup2) {
		set("backup2", backup2);
	}
	
	public String getBackup2() {
		return getStr("backup2");
	}

	public void setBackup3(String backup3) {
		set("backup3", backup3);
	}
	
	public String getBackup3() {
		return getStr("backup3");
	}

}
