package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXdAttendanceLogs<M extends BaseXdAttendanceLogs<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}
	
	public Long getId() {
		return getLong("id");
	}

	public void setOid(String oid) {
		set("oid", oid);
	}
	
	public String getOid() {
		return getStr("oid");
	}

	public void setClsName(String clsName) {
		set("cls_name", clsName);
	}
	
	public String getClsName() {
		return getStr("cls_name");
	}

	public void setFieldName(String fieldName) {
		set("field_name", fieldName);
	}
	
	public String getFieldName() {
		return getStr("field_name");
	}

	public void setOldVal(String oldVal) {
		set("old_val", oldVal);
	}
	
	public String getOldVal() {
		return getStr("old_val");
	}

	public void setNewVal(String newVal) {
		set("new_val", newVal);
	}
	
	public String getNewVal() {
		return getStr("new_val");
	}

	public void setCreateUser(String createUser) {
		set("create_user", createUser);
	}
	
	public String getCreateUser() {
		return getStr("create_user");
	}

	public void setCreateTime(String createTime) {
		set("create_time", createTime);
	}
	
	public String getCreateTime() {
		return getStr("create_time");
	}

}
