package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import com.pointlion.annotation.ChangeFields;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXdEdutrain<M extends BaseXdEdutrain<M>> extends Model<M> implements IBean {

	public void setId(String id) {
		set("id", id);
	}
	@ChangeFields(value="id",desc = "id")
	public String getId() {
		return getStr("id");
	}

	public void setEid(String eid) {
		set("eid", eid);
	}
	@ChangeFields(value="eid",desc = "employeeId")
	public String getEid() {
		return getStr("eid");
	}
	public void setEname(java.lang.String ename) {
		set("ename", ename);
	}
	public java.lang.String getEname() {
		return getStr("ename");
	}

	public void setEnrolldate(String enrolldate) {
		set("enrolldate", enrolldate);
	}
	@ChangeFields(value="enrolldate",desc = "入学日期")
	public String getEnrolldate() {
		return getStr("enrolldate");
	}

	public void setGraduatdate(String graduatdate) {
		set("graduatdate", graduatdate);
	}
	@ChangeFields(value="graduatdate",desc = "毕业日期")
	public String getGraduatdate() {
		return getStr("graduatdate");
	}

	public void setTrainOrgname(String trainOrgname) {
		set("trainOrgname", trainOrgname);
	}
	@ChangeFields(value="trainOrgname",desc = "学校/培训机构名称")
	public String getTrainOrgname() {
		return getStr("trainOrgname");
	}

	public void setMajor(String major) {
		set("major", major);
	}
	@ChangeFields(value="major",desc = "专业")
	public String getMajor() {
		return getStr("major");
	}

	public void setEdubg(String edubg) {
		set("edubg", edubg);
	}
	@ChangeFields(value="edubg",desc = "学历")
	public String getEdubg() {
		return getStr("edubg");
	}

	public void setCtime(String ctime) {
		set("ctime", ctime);
	}
	
	public String getCtime() {
		return getStr("ctime");
	}

	public void setCuser(String cuser) {
		set("cuser", cuser);
	}
	
	public String getCuser() {
		return getStr("cuser");
	}

	public void setBackup1(String backup1) {
		set("backup1", backup1);
	}
	
	public String getBackup1() {
		return getStr("backup1");
	}

	public void setBakcup2(String bakcup2) {
		set("bakcup2", bakcup2);
	}
	
	public String getBakcup2() {
		return getStr("bakcup2");
	}

	public void setBackup3(String backup3) {
		set("backup3", backup3);
	}
	
	public String getBackup3() {
		return getStr("backup3");
	}

}
