package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaHotlineUser<M extends BaseOaHotlineUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setHotlinid(java.lang.String hotlinid) {
		set("hotlinid", hotlinid);
	}
	
	public java.lang.String getHotlinid() {
		return getStr("hotlinid");
	}

	public void setStep(java.lang.String step) {
		set("step", step);
	}
	
	public java.lang.String getStep() {
		return getStr("step");
	}

	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}
	
	public java.lang.String getUserid() {
		return getStr("userid");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	public java.lang.String getUsername() {
		return getStr("username");
	}

	public void setOrgid(java.lang.String orgid) {
		set("orgid", orgid);
	}
	
	public java.lang.String getOrgid() {
		return getStr("orgid");
	}

	public void setOrgname(java.lang.String orgname) {
		set("orgname", orgname);
	}
	
	public java.lang.String getOrgname() {
		return getStr("orgname");
	}

	public void setBumphmodel(java.lang.String bumphmodel) {
		set("bumphmodel", bumphmodel);
	}
	
	public java.lang.String getBumphmodel() {
		return getStr("bumphmodel");
	}

	public void setLookornot(java.lang.String lookornot) {
		set("lookornot", lookornot);
	}
	
	public java.lang.String getLookornot() {
		return getStr("lookornot");
	}

	public void setSortnum(java.lang.String sortnum) {
		set("sortnum", sortnum);
	}
	
	public java.lang.String getSortnum() {
		return getStr("sortnum");
	}

	public void setLooked(java.lang.String looked) {
		set("looked", looked);
	}
	
	public java.lang.String getLooked() {
		return getStr("looked");
	}

	public void setIfshow(java.lang.String ifshow) {
		set("ifshow", ifshow);
	}
	
	public java.lang.String getIfshow() {
		return getStr("ifshow");
	}

	public void setLeaderremark(java.lang.String leaderremark) {
		set("leaderremark", leaderremark);
	}
	
	public java.lang.String getLeaderremark() {
		return getStr("leaderremark");
	}

	public void setParentid(java.lang.String parentid) {
		set("parentid", parentid);
	}
	
	public java.lang.String getParentid() {
		return getStr("parentid");
	}

	public void setIfcomplete(java.lang.String ifcomplete) {
		set("ifcomplete", ifcomplete);
	}
	
	public java.lang.String getIfcomplete() {
		return getStr("ifcomplete");
	}

	public void setCompletetime(java.lang.String completetime) {
		set("completetime", completetime);
	}
	
	public java.lang.String getCompletetime() {
		return getStr("completetime");
	}

	public void setCuserid(java.lang.String cuserid) {
		set("cuserid", cuserid);
	}
	
	public java.lang.String getCuserid() {
		return getStr("cuserid");
	}

	public void setCusername(java.lang.String cusername) {
		set("cusername", cusername);
	}
	
	public java.lang.String getCusername() {
		return getStr("cusername");
	}

	public void setCtime(java.lang.String ctime) {
		set("ctime", ctime);
	}
	
	public java.lang.String getCtime() {
		return getStr("ctime");
	}

	public void setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
	}
	
	public java.lang.String getRemarks() {
		return getStr("remarks");
	}

	public void setReadtime(java.lang.String readtime) {
		set("readtime", readtime);
	}
	
	public java.lang.String getReadtime() {
		return getStr("readtime");
	}

	public void setShowqytextarea(java.lang.String showqytextarea) {
		set("showqytextarea", showqytextarea);
	}
	
	public java.lang.String getShowqytextarea() {
		return getStr("showqytextarea");
	}

	public void setButtondesc(java.lang.String buttondesc) {
		set("buttondesc", buttondesc);
	}
	
	public java.lang.String getButtondesc() {
		return getStr("buttondesc");
	}

	public void setButtontype(java.lang.String buttontype) {
		set("buttontype", buttontype);
	}
	
	public java.lang.String getButtontype() {
		return getStr("buttontype");
	}

	public void setStepdesc(java.lang.String stepdesc) {
		set("stepdesc", stepdesc);
	}
	
	public java.lang.String getStepdesc() {
		return getStr("stepdesc");
	}

	public void setBackup1(java.lang.String backup1) {
		set("backup1", backup1);
	}
	
	public java.lang.String getBackup1() {
		return getStr("backup1");
	}

	public void setBackup2(java.lang.String backup2) {
		set("backup2", backup2);
	}
	
	public java.lang.String getBackup2() {
		return getStr("backup2");
	}

	public void setBackup3(java.lang.String backup3) {
		set("backup3", backup3);
	}
	
	public java.lang.String getBackup3() {
		return getStr("backup3");
	}

}
