package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXdRewardPunishmentSummary<M extends BaseXdRewardPunishmentSummary<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}
	
	public Long getId() {
		return getLong("id");
	}

	public void setYear(String year) {
		set("year", year);
	}
	
	public String getYear() {
		return getStr("year");
	}

	public void setMonth(String month) {
		set("month", month);
	}
	
	public String getMonth() {
		return getStr("month");
	}

	public void setDeptId(String deptId) {
		set("dept_id", deptId);
	}
	
	public String getDeptId() {
		return getStr("dept_id");
	}

	public void setDeptName(String deptName) {
		set("dept_name", deptName);
	}
	
	public String getDeptName() {
		return getStr("dept_name");
	}

	public void setQuota(Double quota) {
		set("quota", quota);
	}
	
	public Double getQuota() {
		return getDouble("quota");
	}

	public void setDisableQuota(Double disableQuota) {
		set("disable_quota", disableQuota);
	}
	
	public Double getDisableQuota() {
		return getDouble("disable_quota");
	}

	public void setAbleQuota(Double ableQuota) {
		set("able_quota", ableQuota);
	}
	
	public Double getAbleQuota() {
		return getDouble("able_quota");
	}

	public void setCreateUser(String createUser) {
		set("create_user", createUser);
	}
	
	public String getCreateUser() {
		return getStr("create_user");
	}

	public void setCreateDate(String createDate) {
		set("create_date", createDate);
	}
	
	public String getCreateDate() {
		return getStr("create_date");
	}

}
