package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaQuestions<M extends BaseOaQuestions<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setTestid(java.lang.String testid) {
		set("testid", testid);
	}
	
	public java.lang.String getTestid() {
		return getStr("testid");
	}

	public void setTestquestion(java.lang.String testquestion) {
		set("testquestion", testquestion);
	}
	
	public java.lang.String getTestquestion() {
		return getStr("testquestion");
	}

	public void setQanswer(java.lang.String qanswer) {
		set("qanswer", qanswer);
	}
	
	public java.lang.String getQanswer() {
		return getStr("qanswer");
	}

	public void setQscore(java.lang.String qscore) {
		set("qscore", qscore);
	}
	
	public java.lang.String getQscore() {
		return getStr("qscore");
	}

	public void setCuser(java.lang.String cuser) {
		set("cuser", cuser);
	}
	
	public java.lang.String getCuser() {
		return getStr("cuser");
	}

	public void setCdate(java.lang.String cdate) {
		set("cdate", cdate);
	}
	
	public java.lang.String getCdate() {
		return getStr("cdate");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setSortnum(java.lang.Integer sortnum) {
		set("sortnum", sortnum);
	}
	
	public java.lang.Integer getSortnum() {
		return getInt("sortnum");
	}

}
