package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaMenuDict<M extends BaseOaMenuDict<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setMenuname(java.lang.String menuname) {
		set("menuname", menuname);
	}
	
	public java.lang.String getMenuname() {
		return getStr("menuname");
	}

	public void setParentid(java.lang.String parentid) {
		set("parentid", parentid);
	}
	
	public java.lang.String getParentid() {
		return getStr("parentid");
	}

	public void setSortnum(java.lang.Integer sortnum) {
		set("sortnum", sortnum);
	}
	
	public java.lang.Integer getSortnum() {
		return getInt("sortnum");
	}

}
