package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCrmCustomerRelation<M extends BaseCrmCustomerRelation<M>> extends Model<M> implements IBean {

	public void setId(String id) {
		set("id", id);
	}
	
	public String getId() {
		return getStr("id");
	}

	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}

	public java.lang.String getUserid() {
		return getStr("userid");
	}

	public void setCreateUserName(String createUserName) {
		set("create_user_name", createUserName);
	}
	
	public String getCreateUserName() {
		return getStr("create_user_name");
	}

	public void setOrgId(java.lang.String orgId) {
		set("org_id", orgId);
	}

	public java.lang.String getOrgId() {
		return getStr("org_id");
	}

	public void setOrgName(java.lang.String orgName) {
		set("org_name", orgName);
	}

	public java.lang.String getOrgName() {
		return getStr("org_name");
	}

	public void setCreateTime(String createTime) {
		set("create_time", createTime);
	}
	
	public String getCreateTime() {
		return getStr("create_time");
	}

	public void setIfSubmit(String ifSubmit) {
		set("if_submit", ifSubmit);
	}
	
	public String getIfSubmit() {
		return getStr("if_submit");
	}

	public void setIfComplete(String ifComplete) {
		set("if_complete", ifComplete);
	}
	
	public String getIfComplete() {
		return getStr("if_complete");
	}

	public void setIfAgree(String ifAgree) {
		set("if_agree", ifAgree);
	}
	
	public String getIfAgree() {
		return getStr("if_agree");
	}

	public void setProcInsId(String procInsId) {
		set("proc_ins_id", procInsId);
	}
	
	public String getProcInsId() {
		return getStr("proc_ins_id");
	}

	public void setBusinessUserName(String businessUserName) {
		set("business_user_name", businessUserName);
	}
	
	public String getBusinessUserName() {
		return getStr("business_user_name");
	}

	public void setMobile(String mobile) {
		set("mobile", mobile);
	}
	
	public String getMobile() {
		return getStr("mobile");
	}

	public void setEmail(String email) {
		set("email", email);
	}
	
	public String getEmail() {
		return getStr("email");
	}

	public void setCustomerCode(String customerCode) {
		set("customer_code", customerCode);
	}
	
	public String getCustomerCode() {
		return getStr("customer_code");
	}

	public void setCustomerName(String customerName) {
		set("customer_name", customerName);
	}
	
	public String getCustomerName() {
		return getStr("customer_name");
	}

	public void setStartTime(String startTime) {
		set("start_time", startTime);
	}
	
	public String getStartTime() {
		return getStr("start_time");
	}

	public void setEndTime(String endTime) {
		set("end_time", endTime);
	}
	
	public String getEndTime() {
		return getStr("end_time");
	}

	public void setDes(String des) {
		set("des", des);
	}
	
	public String getDes() {
		return getStr("des");
	}

}
