package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaApplyWorkOvertime<M extends BaseOaApplyWorkOvertime<M>> extends Model<M> implements IBean {

	public void setId(String id) {
		set("id", id);
	}
	
	public String getId() {
		return getStr("id");
	}

	public void setUserid(String userid) {
		set("userid", userid);
	}
	
	public String getUserid() {
		return getStr("userid");
	}

	public void setApplyerName(String applyerName) {
		set("applyer_name", applyerName);
	}
	
	public String getApplyerName() {
		return getStr("applyer_name");
	}

	public void setOrgId(String orgId) {
		set("org_id", orgId);
	}
	
	public String getOrgId() {
		return getStr("org_id");
	}

	public void setOrgName(String orgName) {
		set("org_name", orgName);
	}
	
	public String getOrgName() {
		return getStr("org_name");
	}

	public void setLeaderMessage(String leaderMessage) {
		set("leader_message", leaderMessage);
	}
	
	public String getLeaderMessage() {
		return getStr("leader_message");
	}

	public void setLeader2Message(String leader2Message) {
		set("leader2_message", leader2Message);
	}
	
	public String getLeader2Message() {
		return getStr("leader2_message");
	}

	public void setIfSubmit(String ifSubmit) {
		set("if_submit", ifSubmit);
	}
	
	public String getIfSubmit() {
		return getStr("if_submit");
	}

	public void setIfComplete(String ifComplete) {
		set("if_complete", ifComplete);
	}
	
	public String getIfComplete() {
		return getStr("if_complete");
	}

	public void setIfAgree(String ifAgree) {
		set("if_agree", ifAgree);
	}
	
	public String getIfAgree() {
		return getStr("if_agree");
	}

	public void setProcInsId(String procInsId) {
		set("proc_ins_id", procInsId);
	}
	
	public String getProcInsId() {
		return getStr("proc_ins_id");
	}

	public void setCreateTime(String createTime) {
		set("create_time", createTime);
	}
	
	public String getCreateTime() {
		return getStr("create_time");
	}

	public void setDes(String des) {
		set("des", des);
	}
	
	public String getDes() {
		return getStr("des");
	}

	public void setTitle(String title) {
		set("title", title);
	}
	
	public String getTitle() {
		return getStr("title");
	}

	public void setWorkDate(String workDate) {
		set("work_date", workDate);
	}
	
	public String getWorkDate() {
		return getStr("work_date");
	}

	public void setStartTime(String startTime) {
		set("start_time", startTime);
	}
	
	public String getStartTime() {
		return getStr("start_time");
	}

	public void setEndTime(String endTime) {
		set("end_time", endTime);
	}
	
	public String getEndTime() {
		return getStr("end_time");
	}

	public void setWorkContent(String workContent) {
		set("work_content", workContent);
	}
	
	public String getWorkContent() {
		return getStr("work_content");
	}

	public void setApplyHour(String applyHour) {
		set("apply_hour", applyHour);
	}
	
	public String getApplyHour() {
		return getStr("apply_hour");
	}

	public void setWorkHour(String workHour) {
		set("work_hour", workHour);
	}
	
	public String getWorkHour() {
		return getStr("work_hour");
	}

	public void setCreateUserId(String create_user_id) {
		set("create_user_id", create_user_id);
	}

	public String getCreateUserId() {
		return get("create_user_id");
	}

	public void setCreateUserName(String create_user_name) {
		set("create_user_name", create_user_name);
	}

	public String getCreateUserName() {
		return get("create_user_name");
	}

	public void setCreateOrgId(String create_org_id) {
		set("create_org_id", create_org_id);
	}

	public String getCreateOrgId() {
		return get("create_org_id");
	}

	public void setCreateOrgName(String create_org_name) {
		set("create_org_name", create_org_name);
	}

	public String getCreateOrgName() {
		return get("create_org_name");
	}

}
