package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaWorkPlanRemarks<M extends BaseOaWorkPlanRemarks<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setRamarks(java.lang.String ramarks) {
		set("ramarks", ramarks);
	}
	
	public java.lang.String getRamarks() {
		return getStr("ramarks");
	}

	public void setStartTime(java.lang.String startTime) {
		set("startTime", startTime);
	}
	
	public java.lang.String getStartTime() {
		return getStr("startTime");
	}

	public void setEndTime(java.lang.String endTime) {
		set("endTime", endTime);
	}
	
	public java.lang.String getEndTime() {
		return getStr("endTime");
	}

	public void setCuser(java.lang.String cuser) {
		set("cuser", cuser);
	}
	
	public java.lang.String getCuser() {
		return getStr("cuser");
	}

	public void setCtime(java.lang.String ctime) {
		set("ctime", ctime);
	}
	
	public java.lang.String getCtime() {
		return getStr("ctime");
	}

	public void setState(java.lang.String state) {
		set("state", state);
	}
	
	public java.lang.String getState() {
		return getStr("state");
	}

}
