package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXdWorkHour<M extends BaseXdWorkHour<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}
	
	public Long getId() {
		return getLong("id");
	}

	public void setYear(String year) {
		set("year", year);
	}
	
	public String getYear() {
		return getStr("year");
	}

	public void setMonth(String month) {
		set("month", month);
	}
	
	public String getMonth() {
		return getStr("month");
	}

	public void setYearMonth(String yearMonth) {
		set("year_month", yearMonth);
	}
	
	public String getYearMonth() {
		return getStr("year_month");
	}

	public void setWorkHour(Double workHour) {
		set("work_hour", workHour);
	}
	
	public Double getWorkHour() {
		return getDouble("work_hour");
	}

	public void setCreateUser(String createUser) {
		set("create_user", createUser);
	}
	
	public String getCreateUser() {
		return getStr("create_user");
	}

	public void setCreateTime(String createTime) {
		set("create_time", createTime);
	}
	
	public String getCreateTime() {
		return getStr("create_time");
	}

	public void setUpdateUser(String updateUser) {
		set("update_user", updateUser);
	}
	
	public String getUpdateUser() {
		return getStr("update_user");
	}

	public void setUpdateTime(String updateTime) {
		set("update_time", updateTime);
	}
	
	public String getUpdateTime() {
		return getStr("update_time");
	}

}
