package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaSenddoc<M extends BaseOaSenddoc<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setDtype(java.lang.String dtype) {
		set("dtype", dtype);
	}
	
	public java.lang.String getDtype() {
		return getStr("dtype");
	}

	public void setDnum(java.lang.String dnum) {
		set("dnum", dnum);
	}
	
	public java.lang.String getDnum() {
		return getStr("dnum");
	}

	public void setDyear(java.lang.String dyear) {
		set("dyear", dyear);
	}
	
	public java.lang.String getDyear() {
		return getStr("dyear");
	}

	public void setDnumber(java.lang.String dnumber) {
		set("dnumber", dnumber);
	}
	
	public java.lang.String getDnumber() {
		return getStr("dnumber");
	}

	public void setDsource(java.lang.String dsource) {
		set("dsource", dsource);
	}
	
	public java.lang.String getDsource() {
		return getStr("dsource");
	}

	public void setDtitle(java.lang.String dtitle) {
		set("dtitle", dtitle);
	}
	
	public java.lang.String getDtitle() {
		return getStr("dtitle");
	}

	public void setDmaindelivery(java.lang.String dmaindelivery) {
		set("dmaindelivery", dmaindelivery);
	}
	
	public java.lang.String getDmaindelivery() {
		return getStr("dmaindelivery");
	}

	public void setDcopydelivery(java.lang.String dcopydelivery) {
		set("dcopydelivery", dcopydelivery);
	}
	
	public java.lang.String getDcopydelivery() {
		return getStr("dcopydelivery");
	}

	public void setDfgldids(java.lang.String dfgldids) {
		set("dfgldids", dfgldids);
	}
	
	public java.lang.String getDfgldids() {
		return getStr("dfgldids");
	}

	public void setDfgldnames(java.lang.String dfgldnames) {
		set("dfgldnames", dfgldnames);
	}
	
	public java.lang.String getDfgldnames() {
		return getStr("dfgldnames");
	}

	public void setDfgldyj(java.lang.String dfgldyj) {
		set("dfgldyj", dfgldyj);
	}
	
	public java.lang.String getDfgldyj() {
		return getStr("dfgldyj");
	}

	public void setDsign(java.lang.String dsign) {
		set("dsign", dsign);
	}
	
	public java.lang.String getDsign() {
		return getStr("dsign");
	}

	public void setDsignuserid(java.lang.String dsignuserid) {
		set("dsignuserid", dsignuserid);
	}
	
	public java.lang.String getDsignuserid() {
		return getStr("dsignuserid");
	}

	public void setDsignusername(java.lang.String dsignusername) {
		set("dsignusername", dsignusername);
	}
	
	public java.lang.String getDsignusername() {
		return getStr("dsignusername");
	}

	public void setDsignname(java.lang.String dsignname) {
		set("dsignname", dsignname);
	}
	
	public java.lang.String getDsignname() {
		return getStr("dsignname");
	}

	public void setDsigntime(java.lang.String dsigntime) {
		set("dsigntime", dsigntime);
	}
	
	public java.lang.String getDsigntime() {
		return getStr("dsigntime");
	}

	public void setDofficesure(java.lang.String dofficesure) {
		set("dofficesure", dofficesure);
	}
	
	public java.lang.String getDofficesure() {
		return getStr("dofficesure");
	}

	public void setDofficeuseruserid(java.lang.String dofficeuseruserid) {
		set("dofficeuseruserid", dofficeuseruserid);
	}
	
	public java.lang.String getDofficeuseruserid() {
		return getStr("dofficeuseruserid");
	}

	public void setDofficeuserusername(java.lang.String dofficeuserusername) {
		set("dofficeuserusername", dofficeuserusername);
	}
	
	public java.lang.String getDofficeuserusername() {
		return getStr("dofficeuserusername");
	}

	public void setDofficesurename(java.lang.String dofficesurename) {
		set("dofficesurename", dofficesurename);
	}
	
	public java.lang.String getDofficesurename() {
		return getStr("dofficesurename");
	}

	public void setDofficesuretime(java.lang.String dofficesuretime) {
		set("dofficesuretime", dofficesuretime);
	}
	
	public java.lang.String getDofficesuretime() {
		return getStr("dofficesuretime");
	}

	public void setDhgkscbr(java.lang.String dhgkscbr) {
		set("dhgkscbr", dhgkscbr);
	}
	
	public java.lang.String getDhgkscbr() {
		return getStr("dhgkscbr");
	}

	public void setDhgkscbtime(java.lang.String dhgkscbtime) {
		set("dhgkscbtime", dhgkscbtime);
	}
	
	public java.lang.String getDhgkscbtime() {
		return getStr("dhgkscbtime");
	}

	public void setDhgksfzr(java.lang.String dhgksfzr) {
		set("dhgksfzr", dhgksfzr);
	}
	
	public java.lang.String getDhgksfzr() {
		return getStr("dhgksfzr");
	}

	public void setDhgksfztime(java.lang.String dhgksfztime) {
		set("dhgksfztime", dhgksfztime);
	}
	
	public java.lang.String getDhgksfztime() {
		return getStr("dhgksfztime");
	}

	public void setDzbkscbr(java.lang.String dzbkscbr) {
		set("dzbkscbr", dzbkscbr);
	}
	
	public java.lang.String getDzbkscbr() {
		return getStr("dzbkscbr");
	}

	public void setDzbkscbtime(java.lang.String dzbkscbtime) {
		set("dzbkscbtime", dzbkscbtime);
	}
	
	public java.lang.String getDzbkscbtime() {
		return getStr("dzbkscbtime");
	}

	public void setDzbksfzr(java.lang.String dzbksfzr) {
		set("dzbksfzr", dzbksfzr);
	}
	
	public java.lang.String getDzbksfzr() {
		return getStr("dzbksfzr");
	}

	public void setDzbksfztime(java.lang.String dzbksfztime) {
		set("dzbksfztime", dzbksfztime);
	}
	
	public java.lang.String getDzbksfztime() {
		return getStr("dzbksfztime");
	}

	public void setDztz(java.lang.String dztz) {
		set("dztz", dztz);
	}
	
	public java.lang.String getDztz() {
		return getStr("dztz");
	}

	public void setDfs(java.lang.String dfs) {
		set("dfs", dfs);
	}
	
	public java.lang.String getDfs() {
		return getStr("dfs");
	}

	public void setDprinter(java.lang.String dprinter) {
		set("dprinter", dprinter);
	}
	
	public java.lang.String getDprinter() {
		return getStr("dprinter");
	}

	public void setDchecker(java.lang.String dchecker) {
		set("dchecker", dchecker);
	}
	
	public java.lang.String getDchecker() {
		return getStr("dchecker");
	}

	public void setDsprint(java.lang.String dsprint) {
		set("dsprint", dsprint);
	}
	
	public java.lang.String getDsprint() {
		return getStr("dsprint");
	}

	public void setCuser(java.lang.String cuser) {
		set("cuser", cuser);
	}
	
	public java.lang.String getCuser() {
		return getStr("cuser");
	}

	public void setCuserid(java.lang.String cuserid) {
		set("cuserid", cuserid);
	}
	
	public java.lang.String getCuserid() {
		return getStr("cuserid");
	}

	public void setCtime(java.lang.String ctime) {
		set("ctime", ctime);
	}
	
	public java.lang.String getCtime() {
		return getStr("ctime");
	}

	public void setDhgksids(java.lang.String dhgksids) {
		set("dhgksids", dhgksids);
	}
	
	public java.lang.String getDhgksids() {
		return getStr("dhgksids");
	}

	public void setDhgksnames(java.lang.String dhgksnames) {
		set("dhgksnames", dhgksnames);
	}
	
	public java.lang.String getDhgksnames() {
		return getStr("dhgksnames");
	}

	public void setDhqrids(java.lang.String dhqrids) {
		set("dhqrids", dhqrids);
	}
	
	public java.lang.String getDhqrids() {
		return getStr("dhqrids");
	}

	public void setDhqrnames(java.lang.String dhqrnames) {
		set("dhqrnames", dhqrnames);
	}
	
	public java.lang.String getDhqrnames() {
		return getStr("dhqrnames");
	}

	public void setDhqryj(java.lang.String dhqryj) {
		set("dhqryj", dhqryj);
	}
	
	public java.lang.String getDhqryj() {
		return getStr("dhqryj");
	}

	public void setDhgrids(java.lang.String dhgrids) {
		set("dhgrids", dhgrids);
	}
	
	public java.lang.String getDhgrids() {
		return getStr("dhgrids");
	}

	public void setDhgrnames(java.lang.String dhgrnames) {
		set("dhgrnames", dhgrnames);
	}
	
	public java.lang.String getDhgrnames() {
		return getStr("dhgrnames");
	}

	public void setDhgremarks(java.lang.String dhgremarks) {
		set("dhgremarks", dhgremarks);
	}
	
	public java.lang.String getDhgremarks() {
		return getStr("dhgremarks");
	}

	public void setDqfldids(java.lang.String dqfldids) {
		set("dqfldids", dqfldids);
	}
	
	public java.lang.String getDqfldids() {
		return getStr("dqfldids");
	}

	public void setDqfldnames(java.lang.String dqfldnames) {
		set("dqfldnames", dqfldnames);
	}
	
	public java.lang.String getDqfldnames() {
		return getStr("dqfldnames");
	}

	public void setDqfldremarks(java.lang.String dqfldremarks) {
		set("dqfldremarks", dqfldremarks);
	}
	
	public java.lang.String getDqfldremarks() {
		return getStr("dqfldremarks");
	}

	public void setDfwids(java.lang.String dfwids) {
		set("dfwids", dfwids);
	}
	
	public java.lang.String getDfwids() {
		return getStr("dfwids");
	}

	public void setDfwnames(java.lang.String dfwnames) {
		set("dfwnames", dfwnames);
	}
	
	public java.lang.String getDfwnames() {
		return getStr("dfwnames");
	}

	public void setDwyids(java.lang.String dwyids) {
		set("dwyids", dwyids);
	}
	
	public java.lang.String getDwyids() {
		return getStr("dwyids");
	}

	public void setDwynames(java.lang.String dwynames) {
		set("dwynames", dwynames);
	}
	
	public java.lang.String getDwynames() {
		return getStr("dwynames");
	}

	public void setDnbcyids(java.lang.String dnbcyids) {
		set("dnbcyids", dnbcyids);
	}
	
	public java.lang.String getDnbcyids() {
		return getStr("dnbcyids");
	}

	public void setDnbcynames(java.lang.String dnbcynames) {
		set("dnbcynames", dnbcynames);
	}
	
	public java.lang.String getDnbcynames() {
		return getStr("dnbcynames");
	}

	public void setDnbcyjzrq(java.lang.String dnbcyjzrq) {
		set("dnbcyjzrq", dnbcyjzrq);
	}
	
	public java.lang.String getDnbcyjzrq() {
		return getStr("dnbcyjzrq");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setReceiveid(java.lang.String receiveid) {
		set("receiveid", receiveid);
	}
	
	public java.lang.String getReceiveid() {
		return getStr("receiveid");
	}

	public void setReceivename(java.lang.String receivename) {
		set("receivename", receivename);
	}
	
	public java.lang.String getReceivename() {
		return getStr("receivename");
	}

	public void setReceivenum(java.lang.String receivenum) {
		set("receivenum", receivenum);
	}
	
	public java.lang.String getReceivenum() {
		return getStr("receivenum");
	}

	public void setBackup1(java.lang.String backup1) {
		set("backup1", backup1);
	}
	
	public java.lang.String getBackup1() {
		return getStr("backup1");
	}

	public void setBackup2(java.lang.String backup2) {
		set("backup2", backup2);
	}
	
	public java.lang.String getBackup2() {
		return getStr("backup2");
	}

}
