package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXdRewardPunishmentDetail<M extends BaseXdRewardPunishmentDetail<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}
	
	public Long getId() {
		return getLong("id");
	}

	public void setYear(String year) {
		set("year", year);
	}
	
	public String getYear() {
		return getStr("year");
	}

	public void setMonth(String month) {
		set("month", month);
	}
	
	public String getMonth() {
		return getStr("month");
	}

	public void setDeptId(String deptId) {
		set("dept_id", deptId);
	}
	
	public String getDeptId() {
		return getStr("dept_id");
	}

	public void setDeptName(String deptName) {
		set("dept_name", deptName);
	}
	
	public String getDeptName() {
		return getStr("dept_name");
	}

	public void setUnitId(String unitId) {
		set("unit_id", unitId);
	}
	
	public String getUnitId() {
		return getStr("unit_id");
	}

	public void setUnitName(String unitName) {
		set("unit_name", unitName);
	}
	
	public String getUnitName() {
		return getStr("unit_name");
	}

	public void setProjectId(Integer projectId) {
		set("project_id", projectId);
	}
	
	public Integer getProjectId() {
		return getInt("project_id");
	}

	public void setProjectName(String projectName) {
		set("project_name", projectName);
	}
	
	public String getProjectName() {
		return getStr("project_name");
	}

	public void setEmpName(String empName) {
		set("emp_name", empName);
	}
	
	public String getEmpName() {
		return getStr("emp_name");
	}

	public void setIdnum(String idnum) {
		set("idnum", idnum);
	}
	
	public String getIdnum() {
		return getStr("idnum");
	}

	public void setRewardPunishment(Double rewardPunishment) {
		set("reward_punishment", rewardPunishment);
	}
	
	public Double getRewardPunishment() {
		return getDouble("reward_punishment");
	}

	public void setRemarks(String remarks) {
		set("remarks", remarks);
	}
	
	public String getRemarks() {
		return getStr("remarks");
	}

	public void setCanDistribution(String canDistribution) {
		set("can_distribution", canDistribution);
	}
	
	public String getCanDistribution() {
		return getStr("can_distribution");
	}

	public void setCreateUser(String createUser) {
		set("create_user", createUser);
	}
	
	public String getCreateUser() {
		return getStr("create_user");
	}

	public void setCreateDate(String createDate) {
		set("create_date", createDate);
	}
	
	public String getCreateDate() {
		return getStr("create_date");
	}

}
