package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXdEmployee<M extends BaseXdEmployee<M>> extends Model<M> implements IBean {

	public void setId(String id) {
		set("id", id);
	}
	
	public String getId() {
		return getStr("id");
	}

	public void setName(String name) {
		set("name", name);
	}
	
	public String getName() {
		return getStr("name");
	}

	public void setEmpnum(String empnum) {
		set("empnum", empnum);
	}
	
	public String getEmpnum() {
		return getStr("empnum");
	}

	public void setEmprelation(String emprelation) {
		set("emprelation", emprelation);
	}
	
	public String getEmprelation() {
		return getStr("emprelation");
	}

	public void setGender(Integer gender) {
		set("gender", gender);
	}
	
	public Integer getGender() {
		return getInt("gender");
	}

	public void setMarried(Integer married) {
		set("married", married);
	}
	
	public Integer getMarried() {
		return getInt("married");
	}

	public void setAge(Integer age) {
		set("age", age);
	}
	
	public Integer getAge() {
		return getInt("age");
	}

	public void setNational(String national) {
		set("national", national);
	}
	
	public String getNational() {
		return getStr("national");
	}

	public void setPoliticsstatus(String politicsstatus) {
		set("politicsstatus", politicsstatus);
	}
	
	public String getPoliticsstatus() {
		return getStr("politicsstatus");
	}

	public void setTopedu(String topedu) {
		set("topedu", topedu);
	}
	
	public String getTopedu() {
		return getStr("topedu");
	}

	public void setSpecialty(String specialty) {
		set("specialty", specialty);
	}
	
	public String getSpecialty() {
		return getStr("specialty");
	}

	public void setTopdegree(String topdegree) {
		set("topdegree", topdegree);
	}
	
	public String getTopdegree() {
		return getStr("topdegree");
	}

	public void setIdnum(String Idnum) {
		set("Idnum", Idnum);
	}
	
	public String getIdnum() {
		return getStr("Idnum");
	}

	public void setCensusregister(String censusregister) {
		set("censusregister", censusregister);
	}
	
	public String getCensusregister() {
		return getStr("censusregister");
	}

	public void setCensusregisteraddr(String censusregisteraddr) {
		set("censusregisteraddr", censusregisteraddr);
	}
	
	public String getCensusregisteraddr() {
		return getStr("censusregisteraddr");
	}

	public void setBirthplace(String birthplace) {
		set("birthplace", birthplace);
	}
	
	public String getBirthplace() {
		return getStr("birthplace");
	}

	public void setPresentaddr(String presentaddr) {
		set("presentaddr", presentaddr);
	}
	
	public String getPresentaddr() {
		return getStr("presentaddr");
	}

	public void setNativeplace(String nativeplace) {
		set("nativeplace", nativeplace);
	}
	
	public String getNativeplace() {
		return getStr("nativeplace");
	}

	public void setTel(String tel) {
		set("tel", tel);
	}
	
	public String getTel() {
		return getStr("tel");
	}

	public void setRetiretime(String retiretime) {
		set("retiretime", retiretime);
	}
	
	public String getRetiretime() {
		return getStr("retiretime");
	}

	public void setIssoldier(Integer issoldier) {
		set("issoldier", issoldier);
	}
	
	public Integer getIssoldier() {
		return getInt("issoldier");
	}

	public void setEntrytime(String entrytime) {
		set("entrytime", entrytime);
	}
	
	public String getEntrytime() {
		return getStr("entrytime");
	}

	public void setDepartime(String departime) {
		set("departime", departime);
	}
	
	public String getDepartime() {
		return getStr("departime");
	}

	public void setInductionstatus(Integer inductionstatus) {
		set("inductionstatus", inductionstatus);
	}
	
	public Integer getInductionstatus() {
		return getInt("inductionstatus");
	}

	public void setDepartment(Integer department) {
		set("department", department);
	}
	
	public Integer getDepartment() {
		return getInt("department");
	}

	public void setUnitname(Integer unitname) {
		set("unitname", unitname);
	}
	
	public Integer getUnitname() {
		return getInt("unitname");
	}

	public void setCostitem(Integer costitem) {
		set("costitem", costitem);
	}
	
	public Integer getCostitem() {
		return getInt("costitem");
	}

	public void setPosition(Integer position) {
		set("position", position);
	}
	
	public Integer getPosition() {
		return getInt("position");
	}

	public void setProtechgrade(String protechgrade) {
		set("protechgrade", protechgrade);
	}
	
	public String getProtechgrade() {
		return getStr("protechgrade");
	}

	public void setVocaqualifilevel(String vocaqualifilevel) {
		set("vocaqualifilevel", vocaqualifilevel);
	}
	
	public String getVocaqualifilevel() {
		return getStr("vocaqualifilevel");
	}

	public void setWorkstation(String workstation) {
		set("workstation", workstation);
	}
	
	public String getWorkstation() {
		return getStr("workstation");
	}

	public void setProtechposts(String protechposts) {
		set("protechposts", protechposts);
	}
	
	public String getProtechposts() {
		return getStr("protechposts");
	}

	public void setVocaQualifilevel1(String vocaQualifilevel1) {
		set("vocaQualifilevel1", vocaQualifilevel1);
	}
	
	public String getVocaQualifilevel1() {
		return getStr("vocaQualifilevel1");
	}

	public void setCertificates(String certificates) {
		set("certificates", certificates);
	}
	
	public String getCertificates() {
		return getStr("certificates");
	}

	public void setContractstartdate(String contractstartdate) {
		set("contractstartdate", contractstartdate);
	}
	
	public String getContractstartdate() {
		return getStr("contractstartdate");
	}

	public void setContractenddate(String contractenddate) {
		set("contractenddate", contractenddate);
	}
	
	public String getContractenddate() {
		return getStr("contractenddate");
	}

	public void setSeniority(String seniority) {
		set("seniority", seniority);
	}
	
	public String getSeniority() {
		return getStr("seniority");
	}

	public void setContractclauses(Integer contractclauses) {
		set("contractclauses", contractclauses);
	}
	
	public Integer getContractclauses() {
		return getInt("contractclauses");
	}

	public void setContractnature(String contractnature) {
		set("contractnature", contractnature);
	}
	
	public String getContractnature() {
		return getStr("contractnature");
	}

	public void setWorktime(String worktime) {
		set("worktime", worktime);
	}
	
	public String getWorktime() {
		return getStr("worktime");
	}

	public void setEmcontact(String emcontact) {
		set("emcontact", emcontact);
	}
	
	public String getEmcontact() {
		return getStr("emcontact");
	}

	public void setRecruitsource(String recruitsource) {
		set("recruitsource", recruitsource);
	}
	
	public String getRecruitsource() {
		return getStr("recruitsource");
	}

	public void setHardstaff(Integer hardstaff) {
		set("hardstaff", hardstaff);
	}
	
	public Integer getHardstaff() {
		return getInt("hardstaff");
	}

	public void setSalary(Integer salary) {
		set("salary", salary);
	}
	
	public Integer getSalary() {
		return getInt("salary");
	}

	public void setCtime(String ctime) {
		set("ctime", ctime);
	}
	
	public String getCtime() {
		return getStr("ctime");
	}

	public void setCuser(String cuser) {
		set("cuser", cuser);
	}
	
	public String getCuser() {
		return getStr("cuser");
	}

	public void setBackup1(String backup1) {
		set("backup1", backup1);
	}
	
	public String getBackup1() {
		return getStr("backup1");
	}

	public void setBackup2(String backup2) {
		set("backup2", backup2);
	}
	
	public String getBackup2() {
		return getStr("backup2");
	}

	public void setBackup3(String backup3) {
		set("backup3", backup3);
	}
	
	public String getBackup3() {
		return getStr("backup3");
	}

	public void setEdubg1(String edubg1) {
		set("edubg1", edubg1);
	}
	
	public String getEdubg1() {
		return getStr("edubg1");
	}

	public void setSchool1(String school1) {
		set("school1", school1);
	}
	
	public String getSchool1() {
		return getStr("school1");
	}

	public void setMajor1(String major1) {
		set("major1", major1);
	}
	
	public String getMajor1() {
		return getStr("major1");
	}

	public void setEdubg2(String edubg2) {
		set("edubg2", edubg2);
	}
	
	public String getEdubg2() {
		return getStr("edubg2");
	}

	public void setSchool2(String school2) {
		set("school2", school2);
	}
	
	public String getSchool2() {
		return getStr("school2");
	}

	public void setMajor2(String major2) {
		set("major2", major2);
	}
	
	public String getMajor2() {
		return getStr("major2");
	}

	public void setSaladjrecord(String saladjrecord) {
		set("saladjrecord", saladjrecord);
	}
	
	public String getSaladjrecord() {
		return getStr("saladjrecord");
	}

	public void setChrecord(String chrecord) {
		set("chrecord", chrecord);
	}
	
	public String getChrecord() {
		return getStr("chrecord");
	}

}
