package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaBumphUser<M extends BaseOaBumphUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setBumphid(java.lang.String bumphid) {
		set("bumphid", bumphid);
	}
	
	public java.lang.String getBumphid() {
		return getStr("bumphid");
	}

	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}
	
	public java.lang.String getUserid() {
		return getStr("userid");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	public java.lang.String getUsername() {
		return getStr("username");
	}

	public void setOrgid(java.lang.String orgid) {
		set("orgid", orgid);
	}
	
	public java.lang.String getOrgid() {
		return getStr("orgid");
	}

	public void setOrgname(java.lang.String orgname) {
		set("orgname", orgname);
	}
	
	public java.lang.String getOrgname() {
		return getStr("orgname");
	}

	public void setUserposition(java.lang.String userposition) {
		set("userposition", userposition);
	}
	
	public java.lang.String getUserposition() {
		return getStr("userposition");
	}

	public void setBumphmodel(java.lang.String bumphmodel) {
		set("bumphmodel", bumphmodel);
	}
	
	public java.lang.String getBumphmodel() {
		return getStr("bumphmodel");
	}

	public void setLookornot(java.lang.String lookornot) {
		set("lookornot", lookornot);
	}
	
	public java.lang.String getLookornot() {
		return getStr("lookornot");
	}

	public void setSortnum(java.lang.Integer sortnum) {
		set("sortnum", sortnum);
	}
	
	public java.lang.Integer getSortnum() {
		return getInt("sortnum");
	}

	public void setLooked(java.lang.String looked) {
		set("looked", looked);
	}
	
	public java.lang.String getLooked() {
		return getStr("looked");
	}

	public void setIfshow(java.lang.String ifshow) {
		set("ifshow", ifshow);
	}
	
	public java.lang.String getIfshow() {
		return getStr("ifshow");
	}

	public void setLeaderremark(java.lang.String leaderremark) {
		set("leaderremark", leaderremark);
	}
	
	public java.lang.String getLeaderremark() {
		return getStr("leaderremark");
	}

	public void setParentid(java.lang.String parentid) {
		set("parentid", parentid);
	}
	
	public java.lang.String getParentid() {
		return getStr("parentid");
	}

	public void setIfcomplete(java.lang.String ifcomplete) {
		set("ifcomplete", ifcomplete);
	}
	
	public java.lang.String getIfcomplete() {
		return getStr("ifcomplete");
	}

	public void setReadtime(java.lang.String readtime) {
		set("readtime", readtime);
	}
	
	public java.lang.String getReadtime() {
		return getStr("readtime");
	}

	public void setBackup1(java.lang.String backup1) {
		set("backup1", backup1);
	}
	
	public java.lang.String getBackup1() {
		return getStr("backup1");
	}

	public void setBackup2(java.lang.String backup2) {
		set("backup2", backup2);
	}
	
	public java.lang.String getBackup2() {
		return getStr("backup2");
	}

	public void setBackup3(java.lang.String backup3) {
		set("backup3", backup3);
	}
	
	public java.lang.String getBackup3() {
		return getStr("backup3");
	}

	public void setCompletetime(java.lang.String completetime) {
		set("completetime", completetime);
	}
	
	public java.lang.String getCompletetime() {
		return getStr("completetime");
	}

	public void setIflooked(java.lang.String iflooked) {
		set("iflooked", iflooked);
	}
	
	public java.lang.String getIflooked() {
		return getStr("iflooked");
	}

	public void setLooktime(java.lang.String looktime) {
		set("looktime", looktime);
	}
	
	public java.lang.String getLooktime() {
		return getStr("looktime");
	}

	public void setStep(java.lang.String step) {
		set("step", step);
	}
	
	public java.lang.String getStep() {
		return getStr("step");
	}

	public void setCreatetime(java.lang.String createtime) {
		set("createtime", createtime);
	}
	
	public java.lang.String getCreatetime() {
		return getStr("createtime");
	}

	public void setCreateuser(java.lang.String createuser) {
		set("createuser", createuser);
	}
	
	public java.lang.String getCreateuser() {
		return getStr("createuser");
	}

	public void setCreateuserid(java.lang.String createuserid) {
		set("createuserid", createuserid);
	}
	
	public java.lang.String getCreateuserid() {
		return getStr("createuserid");
	}

}
