package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseVEmail<M extends BaseVEmail<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setSubject(java.lang.String subject) {
		set("subject", subject);
	}
	
	public java.lang.String getSubject() {
		return getStr("subject");
	}

	public void setBody(java.lang.String body) {
		set("body", body);
	}
	
	public java.lang.String getBody() {
		return getStr("body");
	}

	public void setTimeflage(java.lang.String timeflage) {
		set("timeflage", timeflage);
	}
	
	public java.lang.String getTimeflage() {
		return getStr("timeflage");
	}

	public void setBcc(java.lang.String bcc) {
		set("bcc", bcc);
	}
	
	public java.lang.String getBcc() {
		return getStr("bcc");
	}

	public void setCc(java.lang.String cc) {
		set("cc", cc);
	}
	
	public java.lang.String getCc() {
		return getStr("cc");
	}

	public void setDc(java.lang.String dc) {
		set("dc", dc);
	}
	
	public java.lang.String getDc() {
		return getStr("dc");
	}

	public void setFuserid(java.lang.String fuserid) {
		set("fuserid", fuserid);
	}
	
	public java.lang.String getFuserid() {
		return getStr("fuserid");
	}

	public void setSuserid(java.lang.String suserid) {
		set("suserid", suserid);
	}
	
	public java.lang.String getSuserid() {
		return getStr("suserid");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setOpstatis(java.lang.String opstatis) {
		set("opstatis", opstatis);
	}
	
	public java.lang.String getOpstatis() {
		return getStr("opstatis");
	}

	public void setPid(java.lang.String pid) {
		set("pid", pid);
	}
	
	public java.lang.String getPid() {
		return getStr("pid");
	}

	public void setSdcount(java.lang.String sdcount) {
		set("sdcount", sdcount);
	}
	
	public java.lang.String getSdcount() {
		return getStr("sdcount");
	}

	public void setAdcount(java.lang.String adcount) {
		set("adcount", adcount);
	}
	
	public java.lang.String getAdcount() {
		return getStr("adcount");
	}

	public void setOperuser(java.lang.String operuser) {
		set("operuser", operuser);
	}
	
	public java.lang.String getOperuser() {
		return getStr("operuser");
	}

	public void setCcid(java.lang.String ccid) {
		set("ccid", ccid);
	}
	
	public java.lang.String getCcid() {
		return getStr("ccid");
	}

	public void setDcid(java.lang.String dcid) {
		set("dcid", dcid);
	}
	
	public java.lang.String getDcid() {
		return getStr("dcid");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setFilenum(java.lang.String filenum) {
		set("filenum", filenum);
	}
	
	public java.lang.String getFilenum() {
		return getStr("filenum");
	}

}
