package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaStepHistory<M extends BaseOaStepHistory<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setOid(java.lang.String oid) {
		set("oid", oid);
	}
	
	public java.lang.String getOid() {
		return getStr("oid");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setActorid(java.lang.String actorid) {
		set("actorid", actorid);
	}
	
	public java.lang.String getActorid() {
		return getStr("actorid");
	}

	public void setActorname(java.lang.String actorname) {
		set("actorname", actorname);
	}
	
	public java.lang.String getActorname() {
		return getStr("actorname");
	}

	public void setActtime(java.lang.String acttime) {
		set("acttime", acttime);
	}
	
	public java.lang.String getActtime() {
		return getStr("acttime");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

	public void setCtime(java.lang.String ctime) {
		set("ctime", ctime);
	}
	
	public java.lang.String getCtime() {
		return getStr("ctime");
	}

	public void setCuser(java.lang.String cuser) {
		set("cuser", cuser);
	}
	
	public java.lang.String getCuser() {
		return getStr("cuser");
	}

}
