package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaQchoice<M extends BaseOaQchoice<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setTid(java.lang.String tid) {
		set("tid", tid);
	}
	
	public java.lang.String getTid() {
		return getStr("tid");
	}

	public void setQid(java.lang.String qid) {
		set("qid", qid);
	}
	
	public java.lang.String getQid() {
		return getStr("qid");
	}

	public void setQchoice(java.lang.String qchoice) {
		set("qchoice", qchoice);
	}
	
	public java.lang.String getQchoice() {
		return getStr("qchoice");
	}

	public void setQchoicecontent(java.lang.String qchoicecontent) {
		set("qchoicecontent", qchoicecontent);
	}
	
	public java.lang.String getQchoicecontent() {
		return getStr("qchoicecontent");
	}

	public void setCuser(java.lang.String cuser) {
		set("cuser", cuser);
	}
	
	public java.lang.String getCuser() {
		return getStr("cuser");
	}

	public void setCtime(java.lang.String ctime) {
		set("ctime", ctime);
	}
	
	public java.lang.String getCtime() {
		return getStr("ctime");
	}

}
