package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseVHotlineLetter<M extends BaseVHotlineLetter<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setNum(java.lang.String num) {
		set("num", num);
	}
	
	public java.lang.String getNum() {
		return getStr("num");
	}

	public void setFromtime(java.lang.String fromtime) {
		set("fromtime", fromtime);
	}
	
	public java.lang.String getFromtime() {
		return getStr("fromtime");
	}

	public void setFromer(java.lang.String fromer) {
		set("fromer", fromer);
	}
	
	public java.lang.String getFromer() {
		return getStr("fromer");
	}

	public void setContact(java.lang.String contact) {
		set("contact", contact);
	}
	
	public java.lang.String getContact() {
		return getStr("contact");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

	public void setCtime(java.lang.String ctime) {
		set("ctime", ctime);
	}
	
	public java.lang.String getCtime() {
		return getStr("ctime");
	}

	public void setFyear(java.lang.String fyear) {
		set("fyear", fyear);
	}
	
	public java.lang.String getFyear() {
		return getStr("fyear");
	}

	public void setFmonth(java.lang.String fmonth) {
		set("fmonth", fmonth);
	}
	
	public java.lang.String getFmonth() {
		return getStr("fmonth");
	}

	public void setFday(java.lang.String fday) {
		set("fday", fday);
	}
	
	public java.lang.String getFday() {
		return getStr("fday");
	}

}
