package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaEdLetter<M extends BaseOaEdLetter<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setLetterdate(java.lang.String letterdate) {
		set("letterdate", letterdate);
	}
	
	public java.lang.String getLetterdate() {
		return getStr("letterdate");
	}

	public void setLetternum(java.lang.String letternum) {
		set("letternum", letternum);
	}
	
	public java.lang.String getLetternum() {
		return getStr("letternum");
	}

	public void setLetters(java.lang.String letters) {
		set("letters", letters);
	}
	
	public java.lang.String getLetters() {
		return getStr("letters");
	}

	public void setLettertel(java.lang.String lettertel) {
		set("lettertel", lettertel);
	}
	
	public java.lang.String getLettertel() {
		return getStr("lettertel");
	}

	public void setLettercontent(java.lang.String lettercontent) {
		set("lettercontent", lettercontent);
	}
	
	public java.lang.String getLettercontent() {
		return getStr("lettercontent");
	}

	public void setLettetype(java.lang.String lettetype) {
		set("lettetype", lettetype);
	}
	
	public java.lang.String getLettetype() {
		return getStr("lettetype");
	}

	public void setLettercbrid(java.lang.String lettercbrid) {
		set("lettercbrid", lettercbrid);
	}
	
	public java.lang.String getLettercbrid() {
		return getStr("lettercbrid");
	}

	public void setLettercbrname(java.lang.String lettercbrname) {
		set("lettercbrname", lettercbrname);
	}
	
	public java.lang.String getLettercbrname() {
		return getStr("lettercbrname");
	}

	public void setLetterbctime(java.lang.String letterbctime) {
		set("letterbctime", letterbctime);
	}
	
	public java.lang.String getLetterbctime() {
		return getStr("letterbctime");
	}

	public void setCuserid(java.lang.String cuserid) {
		set("cuserid", cuserid);
	}
	
	public java.lang.String getCuserid() {
		return getStr("cuserid");
	}

	public void setCusername(java.lang.String cusername) {
		set("cusername", cusername);
	}
	
	public java.lang.String getCusername() {
		return getStr("cusername");
	}

	public void setCtime(java.lang.String ctime) {
		set("ctime", ctime);
	}
	
	public java.lang.String getCtime() {
		return getStr("ctime");
	}

	public void setBackup1(java.lang.String backup1) {
		set("backup1", backup1);
	}
	
	public java.lang.String getBackup1() {
		return getStr("backup1");
	}

	public void setBackup2(java.lang.String backup2) {
		set("backup2", backup2);
	}
	
	public java.lang.String getBackup2() {
		return getStr("backup2");
	}

	public void setBackup3(java.lang.String backup3) {
		set("backup3", backup3);
	}
	
	public java.lang.String getBackup3() {
		return getStr("backup3");
	}

}
