package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaTest<M extends BaseOaTest<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setTestname(java.lang.String testname) {
		set("testname", testname);
	}
	
	public java.lang.String getTestname() {
		return getStr("testname");
	}

	public void setScore(java.lang.String score) {
		set("score", score);
	}
	
	public java.lang.String getScore() {
		return getStr("score");
	}

	public void setTestdatetime(java.lang.String testdatetime) {
		set("testdatetime", testdatetime);
	}
	
	public java.lang.String getTestdatetime() {
		return getStr("testdatetime");
	}

	public void setCuser(java.lang.String cuser) {
		set("cuser", cuser);
	}
	
	public java.lang.String getCuser() {
		return getStr("cuser");
	}

	public void setCtime(java.lang.String ctime) {
		set("ctime", ctime);
	}
	
	public java.lang.String getCtime() {
		return getStr("ctime");
	}

	public void setIfpublish(java.lang.String ifpublish) {
		set("ifpublish", ifpublish);
	}
	
	public java.lang.String getIfpublish() {
		return getStr("ifpublish");
	}

	public void setPublisher(java.lang.String publisher) {
		set("publisher", publisher);
	}
	
	public java.lang.String getPublisher() {
		return getStr("publisher");
	}

	public void setPublisherid(java.lang.String publisherid) {
		set("publisherid", publisherid);
	}
	
	public java.lang.String getPublisherid() {
		return getStr("publisherid");
	}

	public void setTesttype(java.lang.String testtype) {
		set("testtype", testtype);
	}
	
	public java.lang.String getTesttype() {
		return getStr("testtype");
	}

	public void setTestersids(java.lang.String testersids) {
		set("testersids", testersids);
	}
	
	public java.lang.String getTestersids() {
		return getStr("testersids");
	}

	public void setTesters(java.lang.String testers) {
		set("testers", testers);
	}
	
	public java.lang.String getTesters() {
		return getStr("testers");
	}

	public void setTestdepartements(java.lang.String testdepartements) {
		set("testdepartements", testdepartements);
	}
	
	public java.lang.String getTestdepartements() {
		return getStr("testdepartements");
	}

	public void setTestdepartementsids(java.lang.String testdepartementsids) {
		set("testdepartementsids", testdepartementsids);
	}
	
	public java.lang.String getTestdepartementsids() {
		return getStr("testdepartementsids");
	}

}
