package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXdSeniorityAllowance<M extends BaseXdSeniorityAllowance<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}
	
	public Long getId() {
		return getLong("id");
	}

	public void setEmpName(String empName) {
		set("emp_name", empName);
	}
	
	public String getEmpName() {
		return getStr("emp_name");
	}

	public void setIdnum(String idnum) {
		set("idnum", idnum);
	}
	
	public String getIdnum() {
		return getStr("idnum");
	}

	public void setHireDate(String hireDate) {
		set("hire_date", hireDate);
	}
	
	public String getHireDate() {
		return getStr("hire_date");
	}

	public void setExpirationDate(String expirationDate) {
		set("expiration_date", expirationDate);
	}
	
	public String getExpirationDate() {
		return getStr("expiration_date");
	}

	public void setMonth(Integer month) {
		set("month", month);
	}
	
	public Integer getMonth() {
		return getInt("month");
	}

	public void setWorkYear(Double workYear) {
		set("work_year", workYear);
	}
	
	public Double getWorkYear() {
		return getDouble("work_year");
	}

	public void setNewWorkYear(Double newWorkYear) {
		set("new_work_year", newWorkYear);
	}
	
	public Double getNewWorkYear() {
		return getDouble("new_work_year");
	}

	public void setOldWokrYear(Double oldWokrYear) {
		set("old_wokr_year", oldWokrYear);
	}
	
	public Double getOldWokrYear() {
		return getDouble("old_wokr_year");
	}

	public void setOldSenallow(Double oldSenallow) {
		set("old_senallow", oldSenallow);
	}
	
	public Double getOldSenallow() {
		return getDouble("old_senallow");
	}

	public void setAddDepart(Double addDepart) {
		set("add_depart", addDepart);
	}
	
	public Double getAddDepart() {
		return getDouble("add_depart");
	}

	public void setSeniorityAllowance(Double seniorityAllowance) {
		set("seniority_allowance", seniorityAllowance);
	}
	
	public Double getSeniorityAllowance() {
		return getDouble("seniority_allowance");
	}

	public void setEmpNature(String empNature) {
		set("emp_nature", empNature);
	}
	
	public String getEmpNature() {
		return getStr("emp_nature");
	}

	public void setYEAR(Integer YEAR) {
		set("YEAR", YEAR);
	}
	
	public Integer getYEAR() {
		return getInt("YEAR");
	}

	public void setCreateUser(String createUser) {
		set("create_user", createUser);
	}
	
	public String getCreateUser() {
		return getStr("create_user");
	}

	public void setCreateDate(String createDate) {
		set("create_date", createDate);
	}
	
	public String getCreateDate() {
		return getStr("create_date");
	}

}
