package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXdAttendanceDays<M extends BaseXdAttendanceDays<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}
	
	public Long getId() {
		return getLong("id");
	}

	public void setAttendidId(String attendidId) {
		set("attendid_id", attendidId);
	}
	
	public String getAttendidId() {
		return getStr("attendid_id");
	}

	public void setEmpNum(String empNum) {
		set("emp_num", empNum);
	}
	
	public String getEmpNum() {
		return getStr("emp_num");
	}

	public void setEmpName(String empName) {
		set("emp_name", empName);
	}
	
	public String getEmpName() {
		return getStr("emp_name");
	}

	public void setOrdinaryOvertime(String ordinaryOvertime) {
		set("ordinary_overtime", ordinaryOvertime);
	}
	
	public String getOrdinaryOvertime() {
		return getStr("ordinary_overtime");
	}

	public void setNationalOvertime(String nationalOvertime) {
		set("national_overtime", nationalOvertime);
	}
	
	public String getNationalOvertime() {
		return getStr("national_overtime");
	}

	public void setDutyCharge(String dutyCharge) {
		set("duty_charge", dutyCharge);
	}
	
	public String getDutyCharge() {
		return getStr("duty_charge");
	}

	public void setMidshiftDays(String midshiftDays) {
		set("midshift_days", midshiftDays);
	}
	
	public String getMidshiftDays() {
		return getStr("midshift_days");
	}

	public void setNightshiftDays(String nightshiftDays) {
		set("nightshift_days", nightshiftDays);
	}
	
	public String getNightshiftDays() {
		return getStr("nightshift_days");
	}

	public void setHightempAllowance(String hightempAllowance) {
		set("hightemp_allowance", hightempAllowance);
	}
	
	public String getHightempAllowance() {
		return getStr("hightemp_allowance");
	}

	public void setMonshouldWorkdays(String monshouldWorkdays) {
		set("monshould_workdays", monshouldWorkdays);
	}
	
	public String getMonshouldWorkdays() {
		return getStr("monshould_workdays");
	}

	public void setSickeleaveDays(String sickeleaveDays) {
		set("sickeleave_days", sickeleaveDays);
	}
	
	public String getSickeleaveDays() {
		return getStr("sickeleave_days");
	}

	public void setCasualleaveDays(String casualleaveDays) {
		set("casualleave_days", casualleaveDays);
	}
	
	public String getCasualleaveDays() {
		return getStr("casualleave_days");
	}

	public void setAbsencedutyDays(String absencedutyDays) {
		set("absenceduty_days", absencedutyDays);
	}
	
	public String getAbsencedutyDays() {
		return getStr("absenceduty_days");
	}

	public void setAbsentworkDays(String absentworkDays) {
		set("absentwork_days", absentworkDays);
	}
	
	public String getAbsentworkDays() {
		return getStr("absentwork_days");
	}

	public void setRestanleaveDays(String restanleaveDays) {
		set("restanleave_days", restanleaveDays);
	}
	
	public String getRestanleaveDays() {
		return getStr("restanleave_days");
	}

	public void setProofreadDesc(String proofreadDesc) {
		set("proofread_desc", proofreadDesc);
	}
	
	public String getProofreadDesc() {
		return getStr("proofread_desc");
	}

	public void setCreateDate(String createDate) {
		set("create_date", createDate);
	}
	
	public String getCreateDate() {
		return getStr("create_date");
	}

	public void setCreateUser(String createUser) {
		set("create_user", createUser);
	}
	
	public String getCreateUser() {
		return getStr("create_user");
	}

}
