package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaSenddocStep<M extends BaseOaSenddocStep<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setSdid(java.lang.String sdid) {
		set("sdid", sdid);
	}
	
	public java.lang.String getSdid() {
		return getStr("sdid");
	}

	public void setSteps(java.lang.String steps) {
		set("steps", steps);
	}
	
	public java.lang.String getSteps() {
		return getStr("steps");
	}

	public void setSortnum(java.lang.Integer sortnum) {
		set("sortnum", sortnum);
	}
	
	public java.lang.Integer getSortnum() {
		return getInt("sortnum");
	}

	public void setActorsid(java.lang.String actorsid) {
		set("actorsid", actorsid);
	}
	
	public java.lang.String getActorsid() {
		return getStr("actorsid");
	}

	public void setActorsname(java.lang.String actorsname) {
		set("actorsname", actorsname);
	}
	
	public java.lang.String getActorsname() {
		return getStr("actorsname");
	}

	public void setDepartids(java.lang.String departids) {
		set("departids", departids);
	}
	
	public java.lang.String getDepartids() {
		return getStr("departids");
	}

	public void setDepartname(java.lang.String departname) {
		set("departname", departname);
	}
	
	public java.lang.String getDepartname() {
		return getStr("departname");
	}

	public void setIfshow(java.lang.String ifshow) {
		set("ifshow", ifshow);
	}
	
	public java.lang.String getIfshow() {
		return getStr("ifshow");
	}

	public void setIfcomplete(java.lang.String ifcomplete) {
		set("ifcomplete", ifcomplete);
	}
	
	public java.lang.String getIfcomplete() {
		return getStr("ifcomplete");
	}

	public void setCompletetime(java.lang.String completetime) {
		set("completetime", completetime);
	}
	
	public java.lang.String getCompletetime() {
		return getStr("completetime");
	}

	public void setParentid(java.lang.String parentid) {
		set("parentid", parentid);
	}
	
	public java.lang.String getParentid() {
		return getStr("parentid");
	}

	public void setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
	}
	
	public java.lang.String getRemarks() {
		return getStr("remarks");
	}

	public void setCuserid(java.lang.String cuserid) {
		set("cuserid", cuserid);
	}
	
	public java.lang.String getCuserid() {
		return getStr("cuserid");
	}

	public void setCusername(java.lang.String cusername) {
		set("cusername", cusername);
	}
	
	public java.lang.String getCusername() {
		return getStr("cusername");
	}

	public void setCtime(java.lang.String ctime) {
		set("ctime", ctime);
	}
	
	public java.lang.String getCtime() {
		return getStr("ctime");
	}

	public void setBackup1(java.lang.String backup1) {
		set("backup1", backup1);
	}
	
	public java.lang.String getBackup1() {
		return getStr("backup1");
	}

	public void setBackup2(java.lang.String backup2) {
		set("backup2", backup2);
	}
	
	public java.lang.String getBackup2() {
		return getStr("backup2");
	}

	public void setBackup3(java.lang.String backup3) {
		set("backup3", backup3);
	}
	
	public java.lang.String getBackup3() {
		return getStr("backup3");
	}

}
