package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaTestresult<M extends BaseOaTestresult<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setTid(java.lang.String tid) {
		set("tid", tid);
	}
	
	public java.lang.String getTid() {
		return getStr("tid");
	}

	public void setAnswers(java.lang.String answers) {
		set("answers", answers);
	}
	
	public java.lang.String getAnswers() {
		return getStr("answers");
	}

	public void setAnswersid(java.lang.String answersid) {
		set("answersid", answersid);
	}
	
	public java.lang.String getAnswersid() {
		return getStr("answersid");
	}

	public void setScore(java.lang.String score) {
		set("score", score);
	}
	
	public java.lang.String getScore() {
		return getStr("score");
	}

	public void setUsetimes(java.lang.String usetimes) {
		set("usetimes", usetimes);
	}
	
	public java.lang.String getUsetimes() {
		return getStr("usetimes");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

}
