package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaMeetroom<M extends BaseOaMeetroom<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setRoomname(java.lang.String roomname) {
		set("roomname", roomname);
	}
	
	public java.lang.String getRoomname() {
		return getStr("roomname");
	}

	public void setRoomnum(java.lang.String roomnum) {
		set("roomnum", roomnum);
	}
	
	public java.lang.String getRoomnum() {
		return getStr("roomnum");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setRoomcpn(java.lang.String roomcpn) {
		set("roomcpn", roomcpn);
	}
	
	public java.lang.String getRoomcpn() {
		return getStr("roomcpn");
	}

	public void setStarttime(java.lang.String starttime) {
		set("starttime", starttime);
	}
	
	public java.lang.String getStarttime() {
		return getStr("starttime");
	}

	public void setEndtime(java.lang.String endtime) {
		set("endtime", endtime);
	}
	
	public java.lang.String getEndtime() {
		return getStr("endtime");
	}

}
