package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXdEffict<M extends BaseXdEffict<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	public void setEid(String eid) {
		set("eid", eid);
	}
	
	public String getEid() {
		return getStr("eid");
	}

	public void setEmpNum(String empNum) {
		set("emp_num", empNum);
	}
	
	public String getEmpNum() {
		return getStr("emp_num");
	}

	public void setEmpName(String empName) {
		set("emp_name", empName);
	}
	
	public String getEmpName() {
		return getStr("emp_name");
	}

	public void setHireDate(String hireDate) {
		set("hire_date", hireDate);
	}
	
	public String getHireDate() {
		return getStr("hire_date");
	}

	public void setAdjustReason(String adjustReason) {
		set("adjust_reason", adjustReason);
	}
	
	public String getAdjustReason() {
		return getStr("adjust_reason");
	}

	public void setOldDeptId(String oldDeptId) {
		set("old_dept_id", oldDeptId);
	}
	
	public String getOldDeptId() {
		return getStr("old_dept_id");
	}

	public void setOldDeptName(String oldDeptName) {
		set("old_dept_name", oldDeptName);
	}
	
	public String getOldDeptName() {
		return getStr("old_dept_name");
	}

	public void setOldPdvalue(String oldPdvalue) {
		set("old_pdValue", oldPdvalue);
	}
	
	public String getOldPdvalue() {
		return getStr("old_pdValue");
	}

	public void setOldPdname(String oldPdname) {
		set("old_pdName", oldPdname);
	}
	
	public String getOldPdname() {
		return getStr("old_pdName");
	}

	public void setOldSalaryLevel(String oldSalaryLevel) {
		set("old_salary_level", oldSalaryLevel);
	}
	
	public String getOldSalaryLevel() {
		return getStr("old_salary_level");
	}

	public void setOldSalary(Double oldSalary) {
		set("old_salary", oldSalary);
	}
	
	public Double getOldSalary() {
		return getDouble("old_salary");
	}

	public void setNewDeptId(String newDeptId) {
		set("new_dept_id", newDeptId);
	}
	
	public String getNewDeptId() {
		return getStr("new_dept_id");
	}

	public void setNewDeptName(String newDeptName) {
		set("new_dept_name", newDeptName);
	}
	
	public String getNewDeptName() {
		return getStr("new_dept_name");
	}

	public void setNewPdvalue(String newPdvalue) {
		set("new_pdValue", newPdvalue);
	}
	
	public String getNewPdvalue() {
		return getStr("new_pdValue");
	}

	public void setNewPdname(String newPdname) {
		set("new_pdName", newPdname);
	}
	
	public String getNewPdname() {
		return getStr("new_pdName");
	}

	public void setNewSalaryLevel(String newSalaryLevel) {
		set("new_salary_level", newSalaryLevel);
	}
	
	public String getNewSalaryLevel() {
		return getStr("new_salary_level");
	}

	public void setNewSalary(Double newSalary) {
		set("new_salary", newSalary);
	}
	
	public Double getNewSalary() {
		return getDouble("new_salary");
	}

	public void setValues(String values) {
		set("values", values);
	}
	
	public String getValues() {
		return getStr("values");
	}

	public void setEffectDate(String effectDate) {
		set("effect_date", effectDate);
	}
	
	public String getEffectDate() {
		return getStr("effect_date");
	}

	public void setOtherRemarks(String otherRemarks) {
		set("other_remarks", otherRemarks);
	}
	
	public String getOtherRemarks() {
		return getStr("other_remarks");
	}

	public void setFieldtype(Integer fieldtype) {
		set("fieldtype", fieldtype);
	}
	
	public Integer getFieldtype() {
		return getInt("fieldtype");
	}

	public void setStatus(String status) {
		set("status", status);
	}
	
	public String getStatus() {
		return getStr("status");
	}

	public void setRemarks(String remarks) {
		set("remarks", remarks);
	}
	
	public String getRemarks() {
		return getStr("remarks");
	}

	public void setCuser(String cuser) {
		set("cuser", cuser);
	}
	
	public String getCuser() {
		return getStr("cuser");
	}

	public void setCtime(String ctime) {
		set("ctime", ctime);
	}
	
	public String getCtime() {
		return getStr("ctime");
	}

	public void setUuser(String uuser) {
		set("uuser", uuser);
	}
	
	public String getUuser() {
		return getStr("uuser");
	}

	public void setUtime(String utime) {
		set("utime", utime);
	}
	
	public String getUtime() {
		return getStr("utime");
	}

	public void setOveruser(String overuser) {
		set("overuser", overuser);
	}
	
	public String getOveruser() {
		return getStr("overuser");
	}

	public void setOvertime(String overtime) {
		set("overtime", overtime);
	}
	
	public String getOvertime() {
		return getStr("overtime");
	}

	public void setBackup1(String backup1) {
		set("backup1", backup1);
	}
	
	public String getBackup1() {
		return getStr("backup1");
	}

	public void setBackup2(String backup2) {
		set("backup2", backup2);
	}
	
	public String getBackup2() {
		return getStr("backup2");
	}

	public void setBackup3(String backup3) {
		set("backup3", backup3);
	}
	
	public String getBackup3() {
		return getStr("backup3");
	}

}
