package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXdTotalTimeOnline<M extends BaseXdTotalTimeOnline<M>> extends Model<M> implements IBean {

	public void setId(String id) {
		set("id", id);
	}
	
	public String getId() {
		return getStr("id");
	}

	public void setDeptName(String deptName) {
		set("dept_name", deptName);
	}
	
	public String getDeptName() {
		return getStr("dept_name");
	}

	public void setProjectName(String projectName) {
		set("project_name", projectName);
	}
	
	public String getProjectName() {
		return getStr("project_name");
	}

	public void setTime1(Integer time1) {
		set("time1", time1);
	}
	
	public Integer getTime1() {
		return getInt("time1");
	}

	public void setTime2(Integer time2) {
		set("time2", time2);
	}
	
	public Integer getTime2() {
		return getInt("time2");
	}

	public void setTime3(Integer time3) {
		set("time3", time3);
	}
	
	public Integer getTime3() {
		return getInt("time3");
	}

	public void setTime4(Integer time4) {
		set("time4", time4);
	}
	
	public Integer getTime4() {
		return getInt("time4");
	}

	public void setTime5(Integer time5) {
		set("time5", time5);
	}
	
	public Integer getTime5() {
		return getInt("time5");
	}

	public void setTime6(Integer time6) {
		set("time6", time6);
	}
	
	public Integer getTime6() {
		return getInt("time6");
	}

	public void setTime7(Integer time7) {
		set("time7", time7);
	}
	
	public Integer getTime7() {
		return getInt("time7");
	}

	public void setTime8(Integer time8) {
		set("time8", time8);
	}
	
	public Integer getTime8() {
		return getInt("time8");
	}

	public void setTime9(Integer time9) {
		set("time9", time9);
	}
	
	public Integer getTime9() {
		return getInt("time9");
	}

	public void setTime10(Integer time10) {
		set("time10", time10);
	}
	
	public Integer getTime10() {
		return getInt("time10");
	}

	public void setTime11(Integer time11) {
		set("time11", time11);
	}
	
	public Integer getTime11() {
		return getInt("time11");
	}

	public void setTime12(Integer time12) {
		set("time12", time12);
	}
	
	public Integer getTime12() {
		return getInt("time12");
	}

	public void setTime13(Integer time13) {
		set("time13", time13);
	}
	
	public Integer getTime13() {
		return getInt("time13");
	}

	public void setTime14(Integer time14) {
		set("time14", time14);
	}
	
	public Integer getTime14() {
		return getInt("time14");
	}

	public void setTime15(Integer time15) {
		set("time15", time15);
	}
	
	public Integer getTime15() {
		return getInt("time15");
	}

	public void setTime16(Integer time16) {
		set("time16", time16);
	}
	
	public Integer getTime16() {
		return getInt("time16");
	}

	public void setTime17(Integer time17) {
		set("time17", time17);
	}
	
	public Integer getTime17() {
		return getInt("time17");
	}

	public void setTime18(Integer time18) {
		set("time18", time18);
	}
	
	public Integer getTime18() {
		return getInt("time18");
	}

	public void setTime19(Integer time19) {
		set("time19", time19);
	}
	
	public Integer getTime19() {
		return getInt("time19");
	}

	public void setTime20(Integer time20) {
		set("time20", time20);
	}
	
	public Integer getTime20() {
		return getInt("time20");
	}

	public void setTime21(Integer time21) {
		set("time21", time21);
	}
	
	public Integer getTime21() {
		return getInt("time21");
	}

	public void setTime22(Integer time22) {
		set("time22", time22);
	}
	
	public Integer getTime22() {
		return getInt("time22");
	}

	public void setTime23(Integer time23) {
		set("time23", time23);
	}
	
	public Integer getTime23() {
		return getInt("time23");
	}

	public void setTime24(Integer time24) {
		set("time24", time24);
	}
	
	public Integer getTime24() {
		return getInt("time24");
	}

	public void setTime25(Integer time25) {
		set("time25", time25);
	}
	
	public Integer getTime25() {
		return getInt("time25");
	}

	public void setSortnum(java.lang.Integer sortnum) {
		set("sortnum", sortnum);
	}

	public java.lang.Integer getSortnum() {
		return getInt("sortnum");
	}

	public void setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
	}

	public java.lang.String getCreateTime() {
		return getStr("create_time");
	}

}
