package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXdAttendanceSummary<M extends BaseXdAttendanceSummary<M>> extends Model<M> implements IBean {

	public void setId(String id) {
		set("id", id);
	}
	
	public String getId() {
		return getStr("id");
	}

	public void setDeptValue(String deptValue) {
		set("dept_value", deptValue);
	}
	
	public String getDeptValue() {
		return getStr("dept_value");
	}

	public void setDeptName(String deptName) {
		set("dept_name", deptName);
	}
	
	public String getDeptName() {
		return getStr("dept_name");
	}

	public void setUnitValue(String unitValue) {
		set("unit_value", unitValue);
	}
	
	public String getUnitValue() {
		return getStr("unit_value");
	}

	public void setUnitName(String unitName) {
		set("unit_name", unitName);
	}
	
	public String getUnitName() {
		return getStr("unit_name");
	}

	public void setProjectValue(String projectValue) {
		set("project_value", projectValue);
	}
	
	public String getProjectValue() {
		return getStr("project_value");
	}

	public void setProjectName(String projectName) {
		set("project_name", projectName);
	}
	
	public String getProjectName() {
		return getStr("project_name");
	}

	public void setEmpNum(String empNum) {
		set("emp_num", empNum);
	}
	
	public String getEmpNum() {
		return getStr("emp_num");
	}

	public void setEmpId(String empId) {
		set("emp_id", empId);
	}
	
	public String getEmpId() {
		return getStr("emp_id");
	}

	public void setEmpName(String empName) {
		set("emp_name", empName);
	}
	
	public String getEmpName() {
		return getStr("emp_name");
	}

	public void setWorkStation(String workStation) {
		set("work_station", workStation);
	}
	
	public String getWorkStation() {
		return getStr("work_station");
	}

	public void setScheduleYear(String scheduleYear) {
		set("schedule_year", scheduleYear);
	}
	
	public String getScheduleYear() {
		return getStr("schedule_year");
	}

	public void setScheduleMonth(String scheduleMonth) {
		set("schedule_month", scheduleMonth);
	}
	
	public String getScheduleMonth() {
		return getStr("schedule_month");
	}

	public void setScheduleYearMonth(String scheduleYearMonth) {
		set("schedule_year_month", scheduleYearMonth);
	}
	
	public String getScheduleYearMonth() {
		return getStr("schedule_year_month");
	}

	public void setCurmonActworkhours(String curmonActworkhours) {
		set("curmon_actworkhours", curmonActworkhours);
	}
	
	public String getCurmonActworkhours() {
		return getStr("curmon_actworkhours");
	}

	public void setAnnualleaveDays(String annualleaveDays) {
		set("annualleave_days", annualleaveDays);
	}
	
	public String getAnnualleaveDays() {
		return getStr("annualleave_days");
	}

	public void setCurmonWorkhours(String curmonWorkhours) {
		set("curmon_workhours", curmonWorkhours);
	}
	
	public String getCurmonWorkhours() {
		return getStr("curmon_workhours");
	}

	public void setCurmonBalancehours(String curmonBalancehours) {
		set("curmon_balancehours", curmonBalancehours);
	}
	
	public String getCurmonBalancehours() {
		return getStr("curmon_balancehours");
	}

	public void setPremonAccbalancehours(String premonAccbalancehours) {
		set("premon_accbalancehours", premonAccbalancehours);
	}
	
	public String getPremonAccbalancehours() {
		return getStr("premon_accbalancehours");
	}

	public void setCurmonAccbalancehours(String curmonAccbalancehours) {
		set("curmon_accbalancehours", curmonAccbalancehours);
	}
	
	public String getCurmonAccbalancehours() {
		return getStr("curmon_accbalancehours");
	}

	public void setRemarks(String remarks) {
		set("remarks", remarks);
	}
	
	public String getRemarks() {
		return getStr("remarks");
	}

	public void setPerformRewardpunish(String performRewardpunish) {
		set("perform_rewardpunish", performRewardpunish);
	}
	
	public String getPerformRewardpunish() {
		return getStr("perform_rewardpunish");
	}

	public void setHireDate(String hireDate) {
		set("hire_date", hireDate);
	}
	
	public String getHireDate() {
		return getStr("hire_date");
	}

	public void setDimissionDate(String dimissionDate) {
		set("dimission_date", dimissionDate);
	}
	
	public String getDimissionDate() {
		return getStr("dimission_date");
	}

	public void setSpecialDesc(String specialDesc) {
		set("special_desc", specialDesc);
	}
	
	public String getSpecialDesc() {
		return getStr("special_desc");
	}

	public void setCurmonSettlehours(String curmonSettlehours) {
		set("curmon_settlehours", curmonSettlehours);
	}
	
	public String getCurmonSettlehours() {
		return getStr("curmon_settlehours");
	}

	public void setAccSettlehours(String accSettlehours) {
		set("acc_settlehours", accSettlehours);
	}
	
	public String getAccSettlehours() {
		return getStr("acc_settlehours");
	}

	public void setWeeks(String weeks) {
		set("weeks", weeks);
	}
	
	public String getWeeks() {
		return getStr("weeks");
	}

	public void setStatus(String status) {
		set("status", status);
	}
	
	public String getStatus() {
		return getStr("status");
	}

	public void setCreateUser(String createUser) {
		set("create_user", createUser);
	}
	
	public String getCreateUser() {
		return getStr("create_user");
	}

	public void setCreateDate(String createDate) {
		set("create_date", createDate);
	}
	
	public String getCreateDate() {
		return getStr("create_date");
	}

	public void setUpdateUser(String updateUser) {
		set("update_user", updateUser);
	}
	
	public String getUpdateUser() {
		return getStr("update_user");
	}

	public void setUpdateDate(String updateDate) {
		set("update_date", updateDate);
	}
	
	public String getUpdateDate() {
		return getStr("update_date");
	}

}
